### ISSUE TITLE
Amélioration intégration logo + double titre

### ISSUE THREAD

**Issue by ThomasG77** [osm-fr/sotmfr-website#103]
J'ai mergé les dernières PRs et l'aperçu me chiffonne sur 2 points sur le texte en doublon "9–11 juin" en plus du logo  et le "vide" du fait que le logo est décalé à gauche par rapport au centre de la page car il n'y a pas de texte long à côté pour remplir (cf capture ci-dessous).

Bien que critiquant, je ne sais pas ce qui pourrait améliorer ces points au mieux. Proposez des corrections.

![Sélection_920](https://user-images.githubusercontent.com/642120/228967254-a4db6209-d3ed-42c6-a4e2-34ce5c863862.png)

**Comment by JackNUMBER** [comment]
Je peux m'occuper de corriger ça.

Est-ce qu'il y a un web design ou des éléments graphiques qui ont été réalisés ? Je vois par exemple une bannière sur [le compte Twitter](https://twitter.com/sotmfr). Ou est-ce qu'on va améliorer le site petit à petit en fonction des des idées/retours/issues ?

Propositions : 
- utiliser le graphisme en fond de la bannière du compte Twitter
- habiller avec une photo de Marseille (point de vue ou satellite)
- un texte "Conférences et ateliers autour de la cartographie participative sur OpenStreetMap"
- une photo "immersive" d'une conférence passée

**Comment by marcelezd** [comment]
oups j'ai oublié de supprimer le texte de la date.

le logo est à gauche endroit parce qu'il y avait un arrière plan l'année dernière (dans le même style que la bannière twitter mentionnée par @JackNUMBER). Je pense que c'est mieux de mettre un arrière plan plutôt que de centrer le logo.

Personnellement je préfère la carte de la bannière twitter plutôt qu'une photo.

**Comment by vinber** [comment]
![SOTM-2023-twitter-cover-1500x500px](https://user-images.githubusercontent.com/890869/229068813-1cfc98e6-e3ad-4032-95cd-3548a71e87de.png)

**Comment by vinber** [comment]
@JackNUMBER @marcelezd comment peut-on aider pour "décider" et avoir un accueil un peu plus sympa ?

**Comment by JackNUMBER** [comment]
@vinber Même question qu'[ici](https://github.com/osm-fr/sotmfr-website/issues/85#issuecomment-1491534434) Est-ce possible d'avoir la bannière sans texte ni logo dessus et non recardré ? Je ne sais pas qui la réalisée.
Cela permettra d'avoir rapidement un résultat satisfaisant, on pourra améliorer ensuite.

As-tu un préférence dans les choix proposés plus haut ?

**Comment by marcelezd** [comment]
pour la bannière, ce serait bien qu'elle fasse au moins 1920px de large pour éviter qu'elle soit floue, l'image plus haut ne fait que 1500px

**Comment by vinber** [comment]
> Est-ce possible d'avoir la bannière sans texte ni logo dessus et non recardré ? Je ne sais pas qui la réalisée.

je viens de demander, j'avais oublié la première fois :( c'est antoine bardelli je pense ou @gendy54 ?


> As-tu un préférence dans les choix proposés plus haut ?

non, j'avoue que cela me dépasse :) jusqu'à maintenant c'est plutôt resté sur des formats texte et logo

**Comment by vinber** [comment]
vous avez une bannière à cet endroit https://cloud.bardelli.fr/s/TCFTXL4qj5eqSsA?path=%2FKIT%20GRAPHIQUE

est-ce que cela vous convient ?

**Comment by JackNUMBER** [comment]
Je regarde ce qu'on peut faire avec ça 👍

**Comment by JackNUMBER** [comment]
Voici ce que je propose #104

**Comment by ThomasG77** [comment]
J'ai mergé la #104 et déployé en prod.
