### ISSUE TITLE
en responsive, menu 'cassé'

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#105]
![Screenshot_20230415-113809](https://user-images.githubusercontent.com/890869/232206347-9c5fdc63-6c61-415d-acbd-c096252c53e8.jpg)

**Comment by vinber** [comment]
toujours présent même après l'upgrade @JackNUMBER

**Comment by JackNUMBER** [comment]
J'avais prévu de regarder mais je crois que ta PR fix ça

**Comment by JackNUMBER** [comment]
@vinber Ha je pensais que le menu par défaut était maintenant un [offcanvas](https://getbootstrap.com/docs/5.3/components/navbar/#offcanvas).

**Comment by vinber** [comment]
j'ai pas l'impression que cela fonctionne comme sur les autres pages

voici ce que j'ai sur les autres 

![image](https://user-images.githubusercontent.com/890869/233918614-175f154d-5b59-41d5-ad9a-4477f33fb2a1.png)

alors que sur la page d'accueil c'est différent

![image](https://user-images.githubusercontent.com/890869/233918761-bfc0a07c-a789-4d11-a6da-3c3b009e2b9e.png)

**Comment by JackNUMBER** [comment]
C'est un oubli de ma part, corrigé dans #118
