### ISSUE TITLE
Mise à jour vers Bootstrap v5.3

### ISSUE THREAD

**Issue by JackNUMBER** [osm-fr/sotmfr-website#107]
Le site sotmfr 2023 utilise Bootstrap v5.2.3 et la v5.3 est disponible.
Cette mise à jour pourrait aider à résoudre #105 
Les [link utilities](https://getbootstrap.com/docs/5.3/helpers/colored-links/#link-utilities) permettrait d'enlever du style custom sur le footer.

Suivre la [documentation de migration](https://getbootstrap.com/docs/5.3/migration) pour s'assurer que rien ne sera cassé.

**Comment by marcelezd** [comment]
> Les [link utilities](https://getbootstrap.com/docs/5.3/helpers/colored-links/#link-utilities) permettrait d'enlever du style custom sur le footer.

Il y a pas mal de css que l'on pourrait remplacer par bootstrap. Par contre, comme on n'utilise pas de composants donc si on utilise bootstrap sur des éléments que l'on répète (comme la navbar ou le footer) il faut les mettre à jour sur toutes les pages où on les utilise.

Est-ce qu'on remplace tout ce qui est remplaçable par bootstrap ?

Je vais déjà enlever ce qui n'est pas utilisé dans le css

**Comment by JackNUMBER** [comment]
> Il y a pas mal de css que l'on pourrait remplacer par bootstrap. Par contre, comme on n'utilise pas de composants donc si on utilise bootstrap sur des éléments que l'on répète (comme la navbar ou le footer) il faut les mettre à jour sur toutes les pages où on les utilise.

Oui, je ne suis pas sûr que tout le monde soit OK pour complexifier un peu le fonctionnement avec un moteur de templates pour éviter de répéter le code (nécessite l'ajout d'une étape de build).

> Est-ce qu'on remplace tout ce qui est remplaçable par bootstrap ?

On peut le faire au fur et à mesure si on modifie le code d'une section. Mon avis est que passer du temps pour tout refaire à l'identique avec Boostrap sur un projet de cette envergure n'apporterait pas grand chose. Ça reste un site événementiel à multiple profils de contribution et il n'y a pour le moment pas de direction forte sur la contribution.

> Je vais déjà enlever ce qui n'est pas utilisé dans le css

Top, je le ferai aussi si j'en vois en passant.

**Comment by JackNUMBER** [comment]
@marcelezd OK pour upgrade Bootstrap ?

**Comment by vinber** [comment]
si j'ai tout suivi, upgrade est passé, réouvrir si nécessaire
