### ISSUE TITLE
Ajout formulaire d'inscription

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#109]
Bonjour,

Page d'inscription à rajouter. Idem que 2022 concernant le texte
https://sotm2022.openstreetmap.fr/inscription.html

_INSCRIPTION
Si vous rencontrez des problèmes pour vous inscrire avec cette page, utilisez [ce lien](https://openstreetmap.assoconnect.com/collect/description/303968-b-state-of-the-map-france-2023)

Si vous ne l'avez pas déjà fait, cliquez sur le bouton jaune Je participe ! pour vous inscrire._

Les liens en question:
https://openstreetmap.assoconnect.com/collect/description/303968-b-state-of-the-map-france-2023

`<iframe id="iframe_assoconnect" src="https://openstreetmap.assoconnect.com/collect/description/303968-b-state-of-the-map-france-2023?iframe=1" width="100%" style="overflow: hidden; border: 0; max-height: none;" scrolling="no" onload="window.location.href='#iframe_assoconnect'"></iframe><script>window.addEventListener("message", function(event) {if(event.data.action === "iframe.height" && event.origin === "https://openstreetmap.assoconnect.com"){document.getElementById("iframe_assoconnect").height = event.data.height;}});</script><style>#iframe_assoconnect{border: 0}</style>`

Merci bien ;)

**Comment by gendy54** [comment]
Quelqu'un pour merger? @marcelezd @JackNUMBER ?
Il faut lancer rapidement les inscriptions

Merci ;)

**Comment by marcelezd** [comment]
C'est @vinber et @ThomasG77 qui ont les droits pour merge

**Comment by gendy54** [comment]
Merci @marcelezd

**Comment by vinber** [comment]
Je laisse à Thomas, moi je comprends pas grand chose à tout cela

Le 20 avril 2023 20:52:15 GMT+02:00, Donat ROBAUX ***@***.***> a écrit :
>Merci @marcelezd 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/osm-fr/sotmfr-website/issues/109#issuecomment-1516794167
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by vinber** [comment]
c'est fait, merci tout le monde

https://sotm2023.openstreetmap.fr/inscription.html
