### ISSUE TITLE
Logos des soutiens

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#111]
j'ouvre l'issue ici pour 

- [ ] pointer la page 2022 https://sotm2022.openstreetmap.fr/sponsors.html
- [ ] il n'y a pas de partenaires
- [ ] il y a 3 niveaux de sponsors (gros, moyen, petit) -> les logos sont classés comme cela dans le nextcloud de l'association / reprendre les formats de 2022 pour les tailles

**Comment by vinber** [comment]
@tykayn j'ai ouvert l'acces au nextcloud sur la partie logo https://nextcloud.openstreetmap.fr/index.php/s/SwwYtgNzgBR6me8

j'ai pointé la page 2022 pour donner une idée de comment cela a été traité l'année dernière.

**Comment by vinber** [comment]
salut, cela serait chouette de pouvoir publier une première version de la page des soutiens ? @tykayn as-tu une idée de "délais" stp ?

**Comment by tykayn** [comment]
salut, j'ai fait une première version dans la semaine, je peux l'envoyer cet après midi :)

**Comment by vinber** [comment]
je cloture et

**Comment by vinber** [comment]
merci tout le monde
