### ISSUE TITLE
Gestions des droits

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#112]
@JackNUMBER @marcelezd @ThomasG77 @tykayn 

vous avez meilleure connaissance que moi des droits et de ce qu'il vous semble préférable d'avoir sur ce dépot, n'hésitez pas à me dire !

ce que je trouve "bien" c'est le fait d'avoir quand même 2 étapes, celui qui fait, celui qui merge et déploie mais peut-être n'est-ce pas nécessaire au regard de l'enjeu du site (somme tout enjeu pas hyper grave ...) !

@JackNUMBER et @marcelezd j'ai essayé de vous ajouter à l'équipe, par exemple pour que vous puissiez vous assigner des issues et/ou autre droit mais pas réussi :(

@tykain tu as les droits d'écriture

**Comment by vinber** [comment]
ok, l'idée c'est d'avoir 
- plusieurs regards qui comprennent
- plusieurs personnes pour éviter un éventuel bouchon (que nous n'avons pas eu mais au cas où)

il va falloir me guider hein ! je veux bien donner des droits à tout le monde, cela me semblerait même assez cohérent de donnéer tous les droits à tout le monde mais je ne suis pas sur que cela marche comme cela :)

**Comment by vinber** [comment]
@JackNUMBER @marcelezd je ne sais pas comment changer vos droits ... vous n'apparraissez pas dans l'équipe, je ne trouve donc pas le moyen de vous changer les droits ... je creuse @ThomasG77 si tu as une idée !

cela permettrait de faire passer les PR plus rapidement

**Comment by marcelezd** [comment]
la doc pour ajouter quelqu'un est [ici](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository) avec sur [cette page](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization) les actions possibles en fonction des différents rôles

**Comment by vinber** [comment]
Merci, normalement @JackNUMBER et @marcelezd vous avez des droits plus étendus

**Comment by vinber** [comment]
Pour la petite histoire, je ne voyais pas le add (ma faute), je ne cherchais que dans l'équipe..

**Comment by vinber** [comment]
On reste sur la proposition je ne merge PAS ma PR c'est bien cela. Pour l'instant c'est pas technique, seulement par accord

**Comment by JackNUMBER** [comment]
On peut clore cette issue ?
