### ISSUE TITLE
ajouter une page infos pratiques

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#12]
voir sotm2019.openstreetmap.fr, une carte umap, avec les lieux principaux, plus quelques infos pratiques tram, bus, parking.

**Comment by vinber** [comment]
désolé la page y est

**Comment by ThomasG77** [comment]
Si tu parles de https://osm-fr.github.io/sotmfr-website/2020/, il s'avère qu'il y a un lien en haut mais qu'il ne renvoye vers rien pour le moment

**Comment by vinber** [comment]
merci, je viens de le comprendre !!! Je ne suis pas encore hyper à l'aise sur tout cela !
je rouvre donc

**Comment by naomap** [comment]
Je me charge de la carte uMap, que j'ai commencée hier : http://u.osmfr.org/m/425303/
J'ai aussi commencé à rédiger les moyens d'accès sur la page wiki : https://wiki.openstreetmap.org/wiki/FR:State_of_the_Map_France_2020#Moyens_d.27acc.C3.A8s

**Comment by BaptisteDixneuf** [comment]
J'ai initialisé la page (https://osm-fr.github.io/sotmfr-website/2020/infos.html) avec les premières informations.

Je garde le ticket ouvert. On complétera la page dans le temps.

**Comment by naomap** [comment]
Merci d'ajouter un target="_blank" sur les liens vers les sites externes : la carte uMap, le site de l'office du tourisme, le camping 5 étoiles et Destinéo.

**Comment by ThomasG77** [comment]
Puisqu'on y est, en plus de "_blank", il faut normalement utiliser d'autres attributs https://twitter.com/addyosmani/status/1234055782896979968

**Comment by vinber** [comment]
à priori la page infos pratiques existe, je cloture donc
