### ISSUE TITLE
Ajout du programme

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#123]
Hello,

Je vous mets le programme prévisionnel pour stimuler les inscriptions.
[Programme prévisionnel.pdf](https://github.com/osm-fr/sotmfr-website/files/11445813/Programme.previsionnel.pdf)

Donc à afficher dès que possible via un lien de téléchargement.

**Comment by vinber** [comment]
il existe une page dédié pour cela à activer vraisemblablement

**Comment by marcelezd** [comment]
il faut aussi convertir le programme en json

**Comment by vinber** [comment]
en fait on a souvent fait en 2 temps 
- temps 1 le pdf téléchargeable
- temps 2 effectivement la version plus dynamique

**Comment by marcelezd** [comment]
l'année dernière on avait un pdf avec avec la charte graphique (cf https://github.com/osm-fr/sotmfr-website/issues/55#issuecomment-1135109267), est-ce qu'on en a un cette année ?

**Comment by lmagreault** [comment]
@gendy54, on diffuse déjà cette version brute ?

**Comment by gendy54** [comment]
Oui oui, le le pdf directement. Il est bon à 98%

**Comment by vinber** [comment]
je ne comprends pas pourquoi ce n'est pas visible en ligne, il y a une étape qui n'est donc pas faite dans le déploiement ?

je croyais que le déploiement était automatique suite au merged ? @ThomasG77 tu peux jeter un oeil stp ?

**Comment by tykayn** [comment]
Je ne sais comment, mais c'est visible en ligne \o/
