### ISSUE TITLE
Préparer le déploiement sur sotm2020.openstreetmap.fr

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#13]
Si nous voulons que le site soit ok pour mardi ou mercredi, autant préparer le déploiement aussi non ?

Comment est-ce que le code fait pour 2020 ici pourra-t-il être visible derrière l'url https://sotm2020.openstreetmap.fr

@jocelynj @Cyrille37

**Comment by DarkVisenya** [comment]
Je peux déployer le site (une fois validé) mardi soir.

**Comment by jocelynj** [comment]
Juste pour confirmer: vous ne déployez pas régulièrement le site de ce git sur sotm2020.openstreetmap.fr ?

**Comment by vinber** [comment]
pas encore, l'idée c'est de remplacer mardi soir le site par le code d'ici.
Ensuite le site sera actualisé depuis ici (enfin je crois mais peut-être faut-il faire autre chose ?). Parce qu'en déployant depuis ici, nous n'hébergeons pas vraiment en fait si ?

**Comment by DarkVisenya** [comment]
Comme les règles sont de conserver le système précédent (c'est à dire du copier-coller du local au serveur), le deployement sera fait uniquement à la main. Donc pas de Jekyll ou autres. 

Je pense que le but du github.io est de juste prévisualiser le code avant le deployement final.

**Comment by vinber** [comment]
ok, peut-on imaginer un déploiement sur sotm2020 avant 21h ? il y a un CA ce soir à 21h, cela permettrait de montrer à tout le monde

**Comment by DarkVisenya** [comment]
Voilà c'est deployé :)

**Comment by vinber** [comment]
✌️

**Comment by vinber** [comment]
je ferme, on est d'accord
