### ISSUE TITLE
déploiement automatisé

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#130]
@jocelynj @ThomasG77 a mis en place un cron qui ne semble pas fonctionner, peux-tu jeter un oeil dessus stp ?

**Comment by vinber** [comment]
cron_pull.sh, un crontab qui ne semble pas s'exécuter (j'écris sous la dictée de Thomas :) ), pas sur de comprendre

**Comment by Marc-marc-marc** [comment]
plusieurs choses : 
- [X] crond fonctionne (le déamon chargé de faire tourner les taches régulières)
- [X] cron a boulu lanncer son script /home/thomasg77/cron_pull.sh
- [ ] le script n'est pas exécutable
- [ ] la fréquence me parait un peu élevé, on risque éventuelement 
- [ ] le script est en erreur
fatal: detected dubious ownership in repository at '/data/project/sotm2023/sotmfr-website'
To add an exception for this directory, call:
1git config --global --add safe.directory /data/project/sotm2023/sotmfr-website
- [ ]  le script pas de détection d'erreur (rajouter`|| { echo "erreur etc" >&2" ; } `pour voir que c'est en erreur

**Comment by Marc-marc-marc** [comment]
le script n'est pas exécutable -> corrigé avec `chmod a+x /home/thomasg77/cron_pull.sh`

**Comment by ThomasG77** [comment]
Je suis au courant pour les actions sur Github/Gitlab mais je n'ai pas la main sur les clés ssh côté serveur.
Conséquence: je ne vois pas comment je pourrais déploier sans cela d'où l'approche cron moins bonne mais réalisable sans avoir de droits supplémentaires. Pour info, je suis passé sur une fréquence toutes les heures coté cron.

**Comment by vinber** [comment]
et donc cela marche ou cela ne marche pas :)

**Comment by jocelynj** [comment]
On peut laisser le cron jusqu'au sotm, qui tourne actuellement toutes les heures. Il faudra juste penser à le désactiver après.
