### ISSUE TITLE
Guide des interventions

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#135]
Bonjour,

Pouvez-vous rajouter le guide des interventions au niveau du programme ?

[SOTM Guide des interventions.pdf](https://github.com/osm-fr/sotmfr-website/files/11618309/SOTM.Guide.des.interventions.pdf)

J'en profite aussi: est ce que le programme pdf qui est en téléchargement peut être affiché sous forme d'image.

Donat

**Comment by gendy54** [comment]
@JackNUMBER En effet non pas besoin. Tu mets ca en prod quand ?
J'en profite. Tu feras attention à bien prendre le programme que je t'avais envoyé. Sur le pdf fait par le graphiste, il y a une coquille le samedi matin à 10h, salle 203. La session sur le RTK dure 1h et il n'y a pas de conf sur le référentiel routier du Gard.
Bon courage ;)

**Comment by JackNUMBER** [comment]
Jusqu'à cette issue on n'avait pas les info sur les conférenciers [demandées ici](https://github.com/osm-fr/sotmfr-website/issues/129#issuecomment-1566204633).
Je suis dessus mais c'est un peu compliqué avec les créneaux qui se chevauchent 😅

C'est noté pour la conf 29 qui n'aura pas lieu.
