### ISSUE TITLE
fonts.gstatic.com sur https://osm-fr.github.io/sotmfr-website/2020/#/

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#14]
Est-ce propre à https://osm-fr.github.io/sotmfr-website/2020/#/ ou va-t-on avoir ce truc aussi sur sotm2020 ?

Peut-on s'en débarasser ?

**Comment by tomao44** [comment]
La connexion au domaine `fonts.gstatic.com` sert à charger la police de caractère [Barlow](https://fonts.google.com/specimen/Barlow).
Cela améliore les performances : [Will web fonts slow down my page?](https://developers.google.com/fonts/faq#will_web_fonts_slow_down_my_page)
Pour le côté vie privée, une partie de réponse : [What does using the Google Fonts API mean for the privacy of my users?](https://developers.google.com/fonts/faq#what_does_using_the_google_fonts_api_mean_for_the_privacy_of_my_users)

**Comment by vinber** [comment]
@tomao44 merci pour les explications et les liens.

Je pense que j'ai un peu de mal dès que je commence à voir "We only see 1 CSS request per font family, per day, per browser."
ce qui je suppose au vu du nombres d'utilisateurs doit représenter quelques millions par jours donc !

"Google Fonts logs records of the CSS and the font file requests, and access to this data is kept secure. Aggregate usage numbers track how popular font families are, and are published on our analytics page. We use data from Google’s web crawler to detect which websites use Google fonts. "
"
et donc cela permet d'adapter notre stratégie et de maintenir notre monopole !

je fais peut-être de la traduction (en mode #traduisonsles) un peu rapide mais je pense important que nous ayons une réflexion sur ces points (je ne bloquerai évidemment pas si nous décidons de continuer à utiliser cet appel à fonts.gstatic.com).

Et franchement je ne saisis pas bien ce que l'on gagne (bon en même temps encor eune fois c'est pas mon taf :) )

**Comment by jocelynj** [comment]
Perso, j'enleverais tout lien vers les fontes google, en la mettant sur le site, ou en n'utilisant pas de fonte spécifique.

Pour info, on avait eu la même question sur http://www.openstreetmap.fr, et on avait enlevé cet appel à google. Par contre, je vois qu'on a maintenant des appels à https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css?ver=2.8.4 et à github pour récupérer la carte.

**Comment by DarkVisenya** [comment]
Une seule font a été conservé et elle est chargé en local, l'utilisation de bibliothèques a été limité à Bootstrap 4, Jquery, Jquery easing, Leaflet.

Je ferme l'issue.
