### ISSUE TITLE
Ajout du Tchat

### ISSUE THREAD

**Issue by tomtoom1978** [osm-fr/sotmfr-website#145]
Salut,
Voici de quoi ajouter le Tchat pour le live / suite demande Priscilla de TomTom et rebond via Benoit.

- C'est dans 1 Iframe / à coller a proximité de la vidéo  sur le site ?!
- C'est directement géré avec le nouveau greffon inclus dans peertube
- Le Tchat englobe les 5 flux lives / la modération est simple.
- Cela servira pour l’ensemble des interventions du SotM.
- j'ai testé vite fait en lançant le code et ca tourne super: [https://dev.k-prod.fr/tchat/](https://dev.k-prod.fr/tchat/)

Voici le code:
_____________________________________________

`<iframe src="https://stream.k-prod.fr/plugins/livechat/router/webchat/room/4193c898-f1ce-42ed-82af-940c5062c088?_ac_mainForeground=%23e0e0e1&amp;_ac_mainBackground=%23222&amp;_ac_greyForeground=%23bbb&amp;_ac_greyBackground=%23464340&amp;_ac_menuForeground=%23fff&amp;_ac_menuBackground=%23000&amp;_ac_inputForeground=%23e0e0e1&amp;_ac_inputBackground=%23222&amp;_ac_buttonForeground=rgb%28255%2C+255%2C+255%29&amp;_ac_buttonBackground=%232e2db3&amp;_ac_link=%23e0e0e1&amp;_ac_linkHover=%23e0e0e1" title="Tchat pour le direct : SOTM FR 2023 - Direct 05 B" sandbox="allow-same-origin allow-scripts allow-popups allow-forms" width="560" height="315" frameborder="0"></iframe>`

**Comment by vinber** [comment]
@marcelezd @JackNUMBER @ThomasG77 @tykayn l'un de vous peut jeter un oeil ?

**Comment by ThomasG77** [comment]
Effectué et déployé
