### ISSUE TITLE
Données structurées des conférences - page Programme

### ISSUE THREAD

**Issue by JackNUMBER** [osm-fr/sotmfr-website#148]
Salut,
j'ai écris le code pour transformer du JSON en HTML pour générer la page des conférences en mode "archive" (vous pouvez le trouver [ici](https://github.com/JackNUMBER/sotmfr-website/tree/conferences-archive/2023)). **J'aurai besoin d'aide pour structurer les données.**

Il y en 15 pour le moment : [conferences.zip](https://github.com/osm-fr/sotmfr-website/files/11729169/conferences.zip)
Je m'appuie sur le guide des intervention de [cette page](https://sotm2023.openstreetmap.fr/programme.html).

Si vous avez un peu de temps pour y participer, merci 👍

**Comment by vinber** [comment]
alors je n'ai pas particulièrement de temps, mais en plus je n'ai même pas compris ce qu'il faudrait faire :D

**Comment by JackNUMBER** [comment]
Fait. La PR arrive.
