### ISSUE TITLE
allez on ouvre la version 2024 ?

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#150]
qui est tenté par donner un coup de main ?

**Comment by gendy54** [comment]
Donc dans les attendus

- [ ] Dates: 28-30 juin 2024
- [ ] Lieu: Université Lyon 3 - Campus Manufacture des Tabacs https://www.openstreetmap.org/way/694531440. https://www.univ-lyon3.fr/manufacture-des-tabacs-1. Lieu pour le vendredi et samedi. Dimanche encore en recherche.
- [ ] Ouvrir la page avec les propositions d'intervention qu'il faut lancer au maximum le 14 mars.

https://framaforms.org/proposition-dintervention-au-sotm-france-2024-1707165686

<a href="https://framaforms.org/proposition-dintervention-au-sotm-france-2024-1707165686">Form</a>"

    <iframe src="https://framaforms.org/proposition-dintervention-au-sotm-france-2024-1707165686" width="100%" height="800" border="0"></iframe>

Go go go ! ;)

Poke @tykayn @tomao44

**Comment by tomao44** [comment]
J'ai travaillé sur la refonte du site afin d'avoir des entêtes, pied de page et navigation séparés du contenu des pages (#151) 
Si ça convient, on peut partir sur cette structure pour le site 2024.

**Comment by dane-lyon** [comment]
@tomao44 merci !

Comment on peut voir le travail réalisé ?

Qui s'occupe de déclencher le site 2024 ? Ce serait bien d'avoir le site rapidement, même s'il n'est pas totalement fourni.

**Comment by vinber** [comment]
@jocelynj de mémoire il faut que tu fasses quelques choses coté nom de domaine, hébergement et certificat

@ThomasG77 l'année dernière tu avais automatisé les déploiements il me semble ?

**Comment by bristow** [comment]
@tomao44 Merci !

Comment on peut voir le travail réalisé ?

Qui s'occupe de déclencher le site 2024 ? Ce serait bien d'avoir le site rapidement, même s'il n'est pas totalement fourni.

**Comment by jocelynj** [comment]
J'ai ajouté le nom de domaine sur Gandi, le proxy, et la VM sotm.vm.openstreetmap.fr

Pour l'instant, le site est vide dans `/data/project/sotm2024/sotmfr-website/2024/`, accessible sur https://sotm2024.openstreetmap.fr/

**Comment by jocelynj** [comment]
En fait, je me suis trompé: l'URL ci-dessus est le site actuel, pas celui proposé par @tomao44.

**Comment by tomao44** [comment]
J'ai créé un workflow pour publier le site sur mon dépôt, voici l'aperçu : https://tomao44.github.io/sotmfr-website/

**Comment by bristow** [comment]
Merci pour cet aperçu 👍

Je ne suis pas fan de la photo de Lyon ou alors il faut arriver à rendre le titre plus lisible car là c'est pas vraiment accessible.

Nous n'avons pas pris encore la décision de partir sur pretalx ou un framaforms, cela devrait être tranché mardi soir au plus tard.

Enfin, ce serait bien qu'on soit quelques uns à pouvoir modifier les fichiers HTML, j'ai vu quelques petites coquilles à modifier. Ce serait bien ensuite que ce soit déployé automatiquement, je sais pas si c'est paramétré ainsi ?

Merci à tous !

**Comment by bristow** [comment]
En fait, la vue de la première page change beaucoup en fonction des résolutions.

![Sélection_1344](https://github.com/osm-fr/sotmfr-website/assets/1156507/b983db22-5b70-4a10-a312-770459526a6d)


![Capture d’écran 2024-03-09 à 10 31 39 resized](https://github.com/osm-fr/sotmfr-website/assets/1156507/e659072c-5cf8-47c6-8f30-ed175f4aa401)
![Capture d’écran 2024-03-09 à 10 31 29 resized](https://github.com/osm-fr/sotmfr-website/assets/1156507/c468ef37-0395-44ca-959c-54183a129dd6)
![Capture d’écran 2024-03-09 à 10 31 06 resized](https://github.com/osm-fr/sotmfr-website/assets/1156507/d8759ee1-06d3-42ea-9ca9-9a05b7319dce)

**Comment by vinber** [comment]
je vous propose que l'on fasse attention à ouvrir des issues cohérentes, plus facile à suivre et fermer :)

merci @jocelynj @tomao44
