### ISSUE TITLE
Déploiement automatisé 2024

### ISSUE THREAD

**Issue by tomao44** [osm-fr/sotmfr-website#154]
Pour le site 2023, il existait une tâche planifiée sur le serveur OpenStreetMap #130 

- [x] publier automatiquement la branche master sur [GitHub Pages](https://osm-fr.github.io/sotmfr-website) 
- [ ] créer une tâche serveur pour publier le [site sur OpenStreetMap](https://sotm2024.openstreetmap.fr/)

**Comment by vinber** [comment]
@tomao44 tu as sans doute besoin de droit pour pouvoir publier ? est-ce que tu as tout ce qu'il te faut ?

**Comment by tomao44** [comment]
> @tomao44 tu as sans doute besoin de droit pour pouvoir publier ? est-ce que tu as tout ce qu'il te faut ?

Effectivement, je n'ai pas accès au serveur pour modifier la tâche planifiée qu'avait fait initialement @ThomasG77 .

**Comment by ThomasG77** [comment]
Prévenez-moi du prochain commit pour que je vérifie sur le serveur.
Normalement, j'ai fait les modifications pour mettre à jour 2024.

**Comment by tomao44** [comment]
@ThomasG77 on est en attente du merge #152

**Comment by vinber** [comment]
@vdct a mergé, rien de visible sur le site pour l'instant. Pas tout à fait automatique donc :)

**Comment by tomao44** [comment]
La publication sur GitHub Pages a bien fonctionné : https://osm-fr.github.io/sotmfr-website/
Pour la tâche, il faut forcément la modifier car le site est généré dans le dossier `dist`.
Voir l'action et le Readme pour plus de détails.

**Comment by ThomasG77** [comment]
Mes droits sur le dépôt git sur `/data/project/sotm2024/sotmfr-website/` ne me permettent pas de correctement faire un pull classique dès qu'il y a des nouveaux fichiers dans le dossier 2024.
Avec le changement impliquant un processus de build, il faut:
- installer Node sur le serveur.
- gérer le processus de build
 
Pour ce dernier cas, soit il faut changer la racine du site côté Nginx à `/data/project/sotm2024/sotmfr-website/dist` et pouvoir exécuter régulièrement le pull et le build dans le dossier via le cron, soit il faut cloner ailleurs et faire des pulls, générer le dist puis copier/déplacer dans `/data/project/sotm2024/sotmfr-website/` via le cron.

J'ai des droits d'accès à la machine mais pas assez étendu pour effectuer ces opérations. Je dois donc laisser la main à @jocelynj.

**Comment by vinber** [comment]
@jocelynj peux tu donner stp les droits aux thomas sur le serveur pour que cela facilite la fluidité ?

**Comment by jocelynj** [comment]
@ThomasG77: je t'ai mis un accès sudo.

Pour l'install de node, je préférerais que tu passes par les paquets deb officiels de node.js, pour faciliter les mises à jour.

Je te laisse changer les chemins dans `/etc/apache2/sites-enabled/sotm2024.conf` comme tu préféres.

**Comment by bristow** [comment]
:wave: à tous !

Je relance une pièce dans la machine ;) Nous allons lancer l'appel à intervention, ce serait bien que le site soit up également au même moment.

Merci !

**Comment by jocelynj** [comment]
@ThomasG77 : est-ce que tu arrives à mettre en place le site ?

Sinon, je peux mettre les fichiers générés en place, si on me donne la procédure, ou directement ces fichiers - @tomao44 ?

**Comment by ThomasG77** [comment]
@jocelynj Désolé, je n'avais pas vu que tu m'avais donné les droits.
@vinber Tout est OK. Le site rafraîchit toutes les heures.
@tomao44 Ferme l'issue si cela te parait satisfaisant sinon dis-moi ce que tu souhaites que je change. On peut toujours discuter d'améliorations sur une issue plus spécifique si nécessaire.

**Comment by bristow** [comment]
Merci !

Demain, on proposera des modifs avec le groupe lyonnais car l'appel à contributions va se faire sur pretalx. Donc faut virer rapidement le framaforms 😁

Mais normalement, je suis développeur, je devrai pouvoir modifier non ?

**Comment by jocelynj** [comment]
Le site m’a l’air bien, merci pour l’install !

Juste quelques remarques:
  - est-il possible de mettre une favicon ? genre celui là: http://sotm2023.openstreetmap.fr/assets/img/favicon.ico
  - peut-on éviter de télécharger des fichiers comme https://mirrors.creativecommons.org/presskit/icons/cc.svg, en le copiant sur sotm2024 ?

**Comment by bristow** [comment]
@ThomasG77 comment fonctionne la mise à jour du site ?

J'ai fait une mise à jour du [footer.html](https://github.com/osm-fr/sotmfr-website/commit/8c276aa8c63a293bd1ecf1735079cd725e2e3a7d), il y a un peu plus d'1h et le site n'est toujours pas mis à jour. 

Une idée ?

**Comment by ThomasG77** [comment]
@bristow Corrigé, une ligne mal reportée dans mon script bash lancé par cron...

**Comment by ThomasG77** [comment]
Oui, toutes les heures en suivant ce pattern dans le cron `0 * * * *`  plus compréhensible via https://crontab.guru/#0_*_*_*_*

**Comment by bristow** [comment]
Ok. 

Tu peux me dire pourquoi le menu n'est pas complet ? On a même pas le retour à la page d'accueil ?

**Comment by ThomasG77** [comment]
L'accueil (https://github.com/osm-fr/sotmfr-website/blob/master/2024/src/html/pages/index.html) s'appuie sur https://github.com/osm-fr/sotmfr-website/blob/master/2024/src/html/layouts/layout.html#L23. Ce layout appelle la navigation https://github.com/osm-fr/sotmfr-website/blob/master/2024/src/html/partials/navigation.html

Pour la partie "Home"/Accueil, c'est caché par la class css `visually-hidden`.

Le reste qui est caché dans le menu du fichier `navigation.html` l'est via la logique en JavaScript dans le fichier https://github.com/osm-fr/sotmfr-website/blob/master/2024/src/js/main.js#L10-L15
Cette logique sert à cacher selon les cas, les éléments qui sont encore en travaux ou qui ne sont pas/plus d'actualités comme le programme, les inscriptions et les sponsors (quand la liste n'est pas encore établie)

PS: je n'ai pas codé cela, n'ayant pour le moment contribué qu'à la partie déploiement (il y a d'autres Thomas qui contribuent à des PR)

**Comment by bristow** [comment]
Merci, c'est très clair !

Tu peux me faire apparaître la page d'accueil ? ou je demande à @tomao44 ?

**Comment by ThomasG77** [comment]
@bristow Fait pour l'accueil

**Comment by bristow** [comment]
On dirait qu'il y a encore un problème dans le déploiement suite à la PR de @Harfeur : https://github.com/osm-fr/sotmfr-website/pull/158

Le site github est ok mais pas le site 2024 🤔

**Comment by ThomasG77** [comment]
@bristow  Je ne vois pas de différence. J'ai loupé quoi? La page sponsors (sous le nom dans le menu Soutiens) est visible comme sur la PR. N'hésite pas à faire une capture d'écran des 2 sites pour mieux comparer si le cas venait à se reproduire.

**Comment by Harfeur** [comment]
>     * peut-on éviter de télécharger des fichiers comme https://mirrors.creativecommons.org/presskit/icons/cc.svg, en le copiant sur sotm2024 ?

Il est préférable de le télécharger depuis une source externe, car si plusieurs sites utilisent le même lien, l'ordinateur aura déjà mis en cache le fichier.

**Comment by bristow** [comment]
> @bristow Je ne vois pas de différence. J'ai loupé quoi? La page sponsors (sous le nom dans le menu Soutiens) est visible comme sur la PR. N'hésite pas à faire une capture d'écran des 2 sites pour mieux comparer si le cas venait à se reproduire.

Ah ben, ça c'est synchronisé on dirait. Bizarre

**Comment by vinber** [comment]
je clôt la partie déploiement automatisé (ici donc)  et on rouvre ensuite des issues quand nécessaire

**Comment by bristow** [comment]
Ok mais hier, on a eu quand même un truc bizarre, le site n'a pas été mis à jour à 21h ou 22h. On verra si problème, on ourvrira une nouvelle issue.

**Comment by bristow** [comment]
Je pense qu'on a vraiment un soucis sur le déploiement automatisé.

J'ai fait 2, 3 modifs ce soir vers 18h et ce n'est toujours pas en ligne.

Quelqu'un peut jeter un oeil ? Merci !

**Comment by ThomasG77** [comment]
@jocelynj Je veux bien regarder le problème mais j'ai "perdu" l'accès. Quand je cherche à me connecter, je me retrouve à la porte avec une erreur du type `ssh: Could not resolve hostname somesubdomain.openstreetmap.fr: Name or service not known`

**Comment by jocelynj** [comment]
Ça marche de mon côté pourtant. Tu fais bien un `ssh sotm.vm.openstreetmap.fr` ?

Le script a l'air de planter parce qu'il ne trouve pas npm: tu l'as installé comment ?
```
Already up to date.
/home/thomasg77/cron_pull.sh: line 9: npm: command not found
/home/thomasg77/cron_pull.sh: line 10: npm: command not found
```

**Comment by ThomasG77** [comment]
J'arrive à me connecter à nouveau. Impossible hier.
`node` et `npm` sont installés via [nvm](https://github.com/nvm-sh/nvm) 

J'ai modifié le fichier `/home/thomasg77/cron_pull.sh` pour rajouter au chemin celui de la version de Node liée à nvm avec
`export PATH=$PATH:/home/thomasg77/.nvm/versions/node/v20.11.1/bin`. J'ai revérifié que les dates des dossiers étaient générés dans `/data/project/sotm2024/sotmfr-website/2024/dist/` et elles correspondent à celle de l'heure d'exécution du cron.
J'attend les prochains changements de code pour qu'on soit sûr que le problème est réellement résolu et on pourra à nouveau fermer l'issue.

**Comment by bristow** [comment]
Je viens de faire une modif du code. À 11h, on aura le verdict. Merci à tous les 2 pour votre réactivité :1st_place_medal:

**Comment by bristow** [comment]
Chouette les modifs sont parfaitement arrivées à 11h, je clos donc cette issue.

Merci !
