### ISSUE TITLE
Simplifier la page d'accueil

### ISSUE THREAD

**Issue by Harfeur** [osm-fr/sotmfr-website#157]
- Moyens de transports
- Hébergements (carte umap)
- Ajouter le logo de l'année
- Image de fond à changer ?

**Comment by vinber** [comment]
Pour mémo, au cas où -> le menu évolue puisque l'on va faire apparaître une entrée inscription (qui doit déja exister mais sans doute commenter pour éviter de la voir pour l;'instant) puis le programme, puis le live

**Comment by bristow** [comment]
Oui, on a vu tout cela, pas de soucis.

**Comment by Jean-BaptisteC** [comment]
L'image de fond et le logo ont été changés.
Et les moyens de transports sont présents sur la page infos.
