### ISSUE TITLE
Améliorer la page Infos Pratiques

### ISSUE THREAD

**Issue by bristow** [osm-fr/sotmfr-website#159]
Simplifier, rajouter des cartes...

**Comment by Jean-BaptisteC** [comment]
Est ce qu'il faudrait encore rajouter des choses ?

**Comment by bristow** [comment]
Je suis en train de préparer une carte uMap mais j'attends un  peu avant de la diffuser.

**Comment by bristow** [comment]
Carte uMap en ligne.

Par contre, il faudrait améliorer la partie haute : 

- vendredi samedi à Lyon3
- dimanche dans les locaux Michelin, cf uMap.

**Comment by Jean-BaptisteC** [comment]
Ce sujet peu être clôturé

**Comment by bristow** [comment]
À la lecture de ce pouet, faudrait améliorer la dernière phrase : https://amicale.net/@cquest/112501535700316127 (un hyperlien vers le bon bus TCL ?)

**Comment by Jean-BaptisteC** [comment]
Est ce que tu sais c'est lesquels
TCL me propose un itinéraire avec 2 bus différents
https://www.tcl.fr/itineraires?date=now&pmr=0&from=stop_area%3Atcl%3ASA%3A5929&to=poi%3Aosm%3Away%3A694531440

**Comment by bristow** [comment]
À priori le 47

https://www.tcl.fr/lignes/bus-47

**Comment by Jean-BaptisteC** [comment]
Le ticket peut être fermé

**Comment by vinber** [comment]
@Jean-BaptisteC je comprends que tu n'as pas le droit de fermer les tickets ? c'est voulu ou pas ?

**Comment by vinber** [comment]
je crois que je t'ai changé les droits pour que tu puisses clore des issues :)

**Comment by vinber** [comment]
si erreur, tu me dis
