### ISSUE TITLE
Texte des liens non visible en mode hover

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/sotmfr-website#160]
![image](https://github.com/osm-fr/sotmfr-website/assets/87148630/5f7d99f6-4e4b-415d-bbd8-1c5242df5b66)

https://github.com/osm-fr/sotmfr-website/blob/607ed82a6f3e8c725e548f95fa2a4158ee479dfc/2024/src/scss/main.css#L24

**Comment by bristow** [comment]
Merci pour l'issue. N'hésite pas à proposer une PR ☺
