### ISSUE TITLE
Premiers ajouts de logos

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#161]
Niveau 1, gros logo
Niveau 2, moyen logo
Niveau 3, petit logo

en partageant les logos ici je ne définis pas leur taille, je vous laisse voir cela.

# Niveau 2

![craig](https://github.com/osm-fr/sotmfr-website/assets/890869/ae0b0479-5912-49df-be62-6491f93d91f0)
![opendatasoft](https://github.com/osm-fr/sotmfr-website/assets/890869/84c856f7-3a0b-479d-8e0b-c2ad32b50fac)
![TomTom-logo-RGB_lockup_lockup](https://github.com/osm-fr/sotmfr-website/assets/890869/23ba82c5-2089-46d5-bc54-44bd74304010)
![makina](https://github.com/osm-fr/sotmfr-website/assets/890869/163f67f5-39d2-4455-b580-8760dd7a5b52)

# Niveau 3

![jawgmaps-blue](https://github.com/osm-fr/sotmfr-website/assets/890869/d8bd3c48-4423-406d-a7f8-2ade7b5079be)
![kprod](https://github.com/osm-fr/sotmfr-website/assets/890869/a5ca7954-0432-4b3f-8b30-0ae01fa1968b)
![Veremes](https://github.com/osm-fr/sotmfr-website/assets/890869/d6739f7b-8e3b-455f-8b2c-f6344f4c0d1d)

# Niveau 3 convention 3 ans, lien avec #69 
![cartocite-3ans](https://github.com/osm-fr/sotmfr-website/assets/890869/cbc4c33f-8948-438c-ad90-ba9c96f3184c)
![magellium-3ans](https://github.com/osm-fr/sotmfr-website/assets/890869/93ffe606-acad-493f-923b-305c2508ed6e)

**Comment by bristow** [comment]
Je viens de [pousser la modif](https://github.com/osm-fr/sotmfr-website/commit/c9f8c4593b8f5da8b131567c1b64d25f680cdded) de la page sponsors, tu me diras si c'est ok, 

Ce sera en ligne à 11h

**Comment by Jean-BaptisteC** [comment]
Michelin et Le Grand Lyon ont été rajoutés ce jour

**Comment by bristow** [comment]
@Jean-BaptisteC peux-tu ajouter de l'espace au dessus du logo Michelin pour respecter les usages du logo dictés par Michelin :

![image](https://github.com/osm-fr/sotmfr-website/assets/1156507/56be797a-1c87-46ec-8e16-9689078c6aa6)

**Comment by Jean-BaptisteC** [comment]
Est ce qu'il ne manquerait pas le logo de Datactivist ?

**Comment by bristow** [comment]
À priori, non, pas de soutien cette année. D'ailleurs, faudrait le supprimer de l'affiche.

**Comment by vinber** [comment]
ajout de latitude en bniveau

**Comment by bristow** [comment]
Faudrait préparer une nouvelle PR pour intégrer le logo de l'urfsit : https://www.wikimedia.fr/wp-content/uploads/2024/01/logo-urfist2020.png

Niveau 2 de soutien.

Merci !

**Comment by bristow** [comment]
Voici le logo de l'urfist en SVG

![urfist_lyon_logo](https://github.com/osm-fr/sotmfr-website/assets/1156507/5b07a690-2835-4511-a4f0-6afecc87ea90)

**Comment by vinber** [comment]
l'urfist de lyon est déja présent, en niveau 3, ce qui est normal

**Comment by Jean-BaptisteC** [comment]
Je mettrai a jour avec le logo en SVG ce soir

**Comment by vinber** [comment]
pardon je n'avais pas vu que c'était pour le passer en svg, je laisse ouvert alors

**Comment by Jean-BaptisteC** [comment]
Peu être fermé, tous les sponsors ont été intégrés
