### ISSUE TITLE
Ajouter le planning à giggity

### ISSUE THREAD

**Issue by bristow** [osm-fr/sotmfr-website#164]
Quand le planning sera réalisé, il faudra faire ajouter à Giggity le planning du SOTM via un PR sur Github

Exemple de PR (JDLL) : https://github.com/Wilm0r/giggity/pull/338/commits/6941ab123c22121b012d631d5db0d09f49457538

Et exemple plus complet dans la doc : https://github.com/Wilm0r/giggity?tab=readme-ov-file#adding-your-event-to-the-default-menu

On pourra rajouter ces URL : 

- Site web : https://sotm2024.openstreetmap.fr/
- Forum : https://forum.openstreetmap.fr/
- Replays à venir : https://peertube.openstreetmap.fr/c/sotm_fr_2024/videos

Peut-être que l'on pourrait aussi rajouter les lieux des journées Vendredi et Samedi, samedi soir, dimanche...

**Comment by Jean-BaptisteC** [comment]
Il pourrait être intéressant d'ajouter un lien vers Google Play ou FDroid sur la page programme pour télécharger l'application Giggity

**Comment by Jean-BaptisteC** [comment]
La PR à été créé [ici](https://github.com/Wilm0r/giggity/pull/347)
Pretalx génère le fichier xml automatiquement.
Il faut juste voir si on héberge le fichier généré pretalx sur notre propre site ou si on fait l'appel au fichier depuis la plateforme pretalx

**Comment by bristow** [comment]
@vinber tu peux créer le chaîne sur PeerTube ? Sur le même modèle que celle de 2023.

Je pense qu'on utilisera le schedule directement sur Pretalx car si on change des confs, ce sera mis à jour automatiquement mais faut mettre un refresh, je sais pas si pretalx répond à cela : 
```
	// To be used only if your event tends to make last-minute changes, and allowed only if the
	// server hosting your Pentabarf file sends HTTP 304s when no changes are made:
	"refresh_interval": 1800,
```

Merci pour le brouillon !

**Comment by Jean-BaptisteC** [comment]
Il semble qu'il y ai des problèmes pour créer la chaine peertube -> https://github.com/osm-fr/infrastructure/issues/558

**Comment by Jean-BaptisteC** [comment]
La PR à été merge sur le dépôt giggity

**Comment by bristow** [comment]
Yep, c'est actif :+1: 

Faudrai juste vérifier qu'il se réactulise quand on fera des modifications !

**Comment by Jean-BaptisteC** [comment]
Sujet clos, peu être fermé

**Comment by bristow** [comment]
J'ai fait une version 1.3 il y a 2 jours et on dirait que le planning n'est pas à jour sur l'App.

J'ai passé le cocktail métro en intervention, vous le voyez vous sur l'App ?

**Comment by Jean-BaptisteC** [comment]
Je le vois de mon côté avec une nouvelle installation.
Depuis le page d'accueil, en faisant un appui long sur l'événement du peu mettre à jour le fichier xml

**Comment by bristow** [comment]
La bonne blague, je n'arrive pas à retourner sur l'accueil, je suis dans la sotm, comme une boucle sans fin :)

**Comment by Jean-BaptisteC** [comment]
Tu n'as que le bouton retour d'Android qui te permet d'y revenir

**Comment by bristow** [comment]
non, ça me quitte l'app. Bon, j'ai supprimé le stockage et c'est bon !
