### ISSUE TITLE
Improve experience on mobile devices

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/sotmfr-website#171]
To planned a trip to Lyon on mobile or tablet, we have only GPS coordinates.
Use GPS coordinates required to copy clipboard and paste in gps.
We can adds url on website, that can be catch by the system and open automatically gps in the right place

Organic Maps and OSMAnd support this:
- https://omaps.app/api
- https://osmand.net/docs/technical/algorithms/osmand-intents/

@bristow WDYT?

**Comment by bristow** [comment]
Yes ! We can improve this part !
