### ISSUE TITLE
Ajout du favicon

### ISSUE THREAD

**Issue by bristow** [osm-fr/sotmfr-website#174]
J'ai essayé de rajouter le favicon (on peut en prendre un là : https://sotm2023.openstreetmap.fr/assets/img/favicon.ico

mais pas compris pourquoi il ne voulait pas s'afficher. À faire donc :)

**Comment by Jean-BaptisteC** [comment]
Il manque une propriété dans le header
https://www.w3schools.com/howto/howto_html_favicon.asp#:~:text=To%20add%20a%20favicon%20to,is%20%22favicon.ico%22.

**Comment by bristow** [comment]
Oui j'avais ajouté cela mais sur mon poste de dev', le favicon ne s'affichait pas mais cela venait peut-être du chemin.
