### ISSUE TITLE
Préparer la page programme

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/sotmfr-website#186]
On peut anticiper la préparation de la page programme, pour n'avoir plus qu'a mettre à jour la barre de navigation et les fichiers au dernier moment.

- Lors de l'ajout dans la barre de navigation, on supprime le lien vers l'appel à contributions ?
- On reste sur le même format que l'année dernière (2 PDF, un programme, et un guide avec un résumé) ?
- Est ce qu'une application mobile est prévue comme l'année dernière ?

CC @bristow @vinber 

Todo:

- [ ] Ajouter le programme en PDF
- [ ] Ajouter le guide des interventions en PDF

**Comment by bristow** [comment]
La page programme sera simplifiée. Un lien vers le PDF si besoin (je sais pas encore si on va le faire faire), et on ajoutera le widget html de Pretalx comme ce qu'il se fait ici : https://jdll.org/programme

L'application mobile sera giggity car ce sera simple à mettre en oeuvre.
