### ISSUE TITLE
Attribution non lisible en page d'accueil

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#19]
l'attribution de la carte n'est pas lisible en page d'accueil, d'autant plus quand on est sur la carte en fond d'image
![Capture d’écran de 2020-03-01 10-26-24](https://user-images.githubusercontent.com/890869/75623104-4d229700-5ba7-11ea-8419-a68419de5b8b.png)

**Comment by DarkVisenya** [comment]
Si je me trompe pas, l'attribution était pour l'ancienne image. Je l'ai retiré dans cet #17

**Comment by tomao44** [comment]
C'est bien ça, j'avais oublié de l'enlever quand j'ai changé l'image #7

**Comment by vinber** [comment]
je ne ferme pas pour permettre à d'autres de voir l'issue, tant qu'elle est visible :)

**Comment by ThomasG77** [comment]
Il y a deux types d'attribution: celle liée à l'auteur de l'image et celle liée à l'usage d'OpenStreetMap si l'image contient une carte.

Avant, on avait une image WIkipedia dont on référençait l'auteur mais pas basé sur un fond OSM. On l'a fait sauter donc on a fait sauter l'attribution associée.
Après, avec la nouvelle image qui contient des données OSM, il reste à priori à rajouter "Les contributeurs OSM" et le crédit pour l'auteur de l'image (je ne sais pas trop qui attribuer par contre)

**Comment by vinber** [comment]
tu as raison, j ene sais pas non plus qui est l'auteur pour la carte, et effectivement il est tout à fait souhaitable de faire apparaitre @ les contributeurs de OpenStreetMap avec l'ulr sur https://www.openstreetmap.org/copyright

**Comment by DarkVisenya** [comment]
J'ai modifié par ça :
![contrib](https://user-images.githubusercontent.com/27078725/75630382-b4ae0600-5bea-11ea-8638-6529396de257.png)

Est-ce que cela vous convient ?

**Comment by BaptisteDixneuf** [comment]
Pull request #17 merged. Je ferme l'issue.
