### ISSUE TITLE
Préparer la page inscription

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/sotmfr-website#190]
- [x] Afficher la page inscription dans le menu de navigation
- [x] Intégrer l'iframe assoconnect

Est ce qu'il y une date butoir pour s'inscrire ?
La veille à minuit ?
Prévoir une pr pour masquer la page d'inscription au dernier moment ? (Se baser sur la même logique que la fonction Javascript contributionCall)

@gendy54

**Comment by vinber** [comment]
il n'y a pas de date butoir pour s'inscrire, parfois les gens continuent le jour de l'ouverture voir pendant le w-e.

**Comment by gendy54** [comment]
Lien du formulaire: https://openstreetmap.assoconnect.com/collect/description/404597-b-state-of-the-map-france-2024

iframe:

<iframe id="iframe_assoconnect" src="https://openstreetmap.assoconnect.com/collect/description/404597-b-state-of-the-map-france-2024?iframe=1" width="100%" style="overflow: hidden; border: 0; max-height: none;" scrolling="no" onload="window.location.href='#iframe_assoconnect'"></iframe><script>window.addEventListener("message", function(event) {if(event.data.action === "iframe.height" && event.origin === "https://openstreetmap.assoconnect.com"){document.getElementById("iframe_assoconnect").height = event.data.height;}});</script><style>#iframe_assoconnect{border: 0}</style>

**Comment by Jean-BaptisteC** [comment]
Merci pour les infos :)
La PR est prête ça peut être poussé quand vous voulez

**Comment by gendy54** [comment]
Je laisse en test le formulaire pour voir si y a des choses à rectifier et ou pourra pousser.
