### ISSUE TITLE
Lister les hébergements disponibles

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/sotmfr-website#197]
A mettre dans une premier temps en masqué sur la page infos et les afficher une fois les chambres Crous écoulées
Todo
- [x] Créer une PR à push dès lors que les chambres Crous sont écoulées

**Comment by Jean-BaptisteC** [comment]
@bristow est ce que tu sais si René à une liste précise avec les urls des sites web ?

**Comment by bristow** [comment]
Tout est là : 

J’ai commencé à explorer des solutions complémentaires en auberge de jeunesse, soit qu’on pourrait prendre par dortoir entier par l’asso (et relouer comme pour les chambres CROUS), soit simplement recommander aux personnes lorsque toutes les chambres du CROUS auront été prises.
[Pilo](https://www.pilohotels.com/)

Montée des Carmélites sur les pentes de la Croix-rousse (40 min. en TC depuis la Manu).
Quelques prix (base 3 nuits) : :

    lit capsule dans un dortoir de 16 personnes : 31.25/nuit/personne
    le dortoir complet de 14 personnes : 442.89/nuit (soit 31.60/p)
    lit capsule dans un dortoir de 4 personnes (sdb privée) : 39.33/nuit/personne
    dortoir complet de 4 personnes (sdb privée) : 157.32/nuit (soit 39.33/p)
    Note : il existe des dortoirs réservés aux femmes aussi.

![image](https://github.com/osm-fr/sotmfr-website/assets/1156507/11e360a7-61c3-4913-aca8-8bafad1a57ce)

[Alter’hostel](https://www.alter-hostel.com/fr)

Quai Pierre Scize vers Vaise (40 min. en TC depuis la Manu).
Prix (base 3 nuits) :

    Lit Superposé dans Dortoir Mixte de 18 Lits : 29.33€/nuit/personne
    Lit Superposé dans Dortoir Mixte de 10 Lits : 31.33€/nuit/personne
    Lit dans Dortoir Mixte de 6 Lits : 37€/nuit/personne

![image](https://github.com/osm-fr/sotmfr-website/assets/1156507/345f8cd6-5411-4166-a0a0-177c9de6f8e9)

[Slo hostel](https://slohostels.com/fr/lyon-saxe/) Rue Bonnefoi

M° Saxe-Gambetta (10 min en métro de la Manu)
Quelques prix :

    Lit dans un dortoir mixte pour 4 personnes : 35.47€/nuit/personne
    Dortoir pour 4 personnes : 141.87€/nuit

![image](https://github.com/osm-fr/sotmfr-website/assets/1156507/f7ad2cbf-3ce5-408c-8146-1ba4879c7aba)


[Slo hostel](https://slohostels.com/fr/lyon-les-pentes/) Pentes de la Croix-Rousse

Rue Alsace-Lorraine M° Hôtel-de-Ville (30 min. depuis la manu en TC)
Quelques prix :

    Lit dans un dortoir mixte pour 10 personnes : 29,77€/nuit/personne
    Lit dans un dortoir mixte pour 6 personnes : 31.67€/nuit/personne
    Dortoir privé pour 6 personnes : 190€/nuit

![image](https://github.com/osm-fr/sotmfr-website/assets/1156507/95483a89-ab62-4362-b9be-90bdcb85ed92)

[Le Flaneur](https://leflaneur-guesthouse.com/)

Rue Sébastien Gryphe (15 min. en TC depuis la Manu)
Quelques prix :

    Lit dans un dortoir mixte pour 16 personnes : 22.83€/nuit/personne
    Lit dans un dortoir mixte pour 10 personnes : 25.83€/nuit/personne
    Remarque : petit-déjeuner inclu

![image](https://github.com/osm-fr/sotmfr-website/assets/1156507/031195e8-1bd9-4c1c-8a23-d9a79d0426d7)


[HO36](https://ho36.com/lyon-guillotiere/)

Rue Montesquieu, Tram Saint-André (15 min. en TC depuis la Manu)
Quelques prix :

    Lit en dortoir mixte de 6 personnes : 23.04€/nuit/personne
    Dortoir entier pour 6 personnes : 126.72€/nuit (soit 21.12/p)

![image](https://github.com/osm-fr/sotmfr-website/assets/1156507/8782378d-0688-4098-bb82-71f3475fa4d7)

Remarque : certains prix sont sans la taxe de séjour : 0,83 €/personne/nuit

**Comment by Jean-BaptisteC** [comment]
Merci pour les infos.
Je vais préparer une PR
Je ne suis pas sûr que ça soit nécessaire de mettre tout le texte et les photos.
Je propose de mettre le nom + hyperlien vers le site web
Et un hyperlien vers l'itinéraire entre le logement et l'université

**Comment by vdct** [comment]
> J’ai commencé à explorer des solutions complémentaires en auberge de jeunesse, soit qu’on pourrait prendre par dortoir entier par l’asso (et relouer comme pour les chambres CROUS), soit simplement recommander aux personnes lorsque toutes les chambres du CROUS auront été prises.

Je pense qu'il faut limiter les efforts de gestion sur ce sujet. Entre les propositions CROUS et la superbe liste complémentaire c'est déjà d'un niveau de service tip top comparé aux precedents SOTM. Gérer les hébergements c'est energivore, on ouvre déjà des inscriptions sur plusieurs sites CROUS, je ne nous vois pas prendre en charge d'autres inscriptions sur encore d'autres sites avec multiplication des interlocuteurs.
Et encore bravo pour le boulot de recensement, vraiment !

**Comment by Jean-BaptisteC** [comment]
Voila une première proposition
![image](https://github.com/osm-fr/sotmfr-website/assets/87148630/060395e0-35ef-4494-9437-21bdb42936b6)

**Comment by bristow** [comment]
C'est chouette, peut-être mettre plutôt le temps en transport en commun ? Je sais pas, tu as trouvé comment ces informations.

Et pour cartes.app, ce serait pas mal si c'est déjà faisable.

**Comment by Jean-BaptisteC** [comment]
Distance fournis par Graphhopper a pied
Cartes.app ne propose pas encore le routage en transport en commun pour Lyon.
Sinon on fait plus simple juste une liste de liens.

**Comment by gendy54** [comment]
Je viens de voir cette page alors que j'ai recrée une issue #221 A voir les hébergements en fin de liste qui ne sont pas dedans je pense.
