### ISSUE TITLE
Préparer la mise en place du live sur la page d'accueil

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/sotmfr-website#199]
Todo:
- [x] Ajouter le stream peertube sur la page d'accueil
- [ ] ~Ajouter le tchat ?~

**Comment by bristow** [comment]
Bonne question pour le tchat !

@jocelynj le plugin tchat est actif sur notre instance OSM ?

**Comment by jocelynj** [comment]
Tu parles bien d’un tchat sur peertube ?

**Comment by bristow** [comment]
oui, le plugin livechat, celui-ci : https://livingston.frama.io/peertube-plugin-livechat/fr/

**Comment by Jean-BaptisteC** [comment]
Voici l'url de l'annnée dernière, si ça peut aider
https://stream.k-prod.fr/plugins/livechat/router/webchat/room/4193c898-f1ce-42ed-82af-940c5062c088?_ac_mainForeground=%23e0e0e1&amp;_ac_mainBackground=%23222&amp;_ac_greyForeground=%23bbb&amp;_ac_greyBackground=%23464340&amp;_ac_menuForeground=%23fff&amp;_ac_menuBackground=%23000&amp;_ac_inputForeground=%23e0e0e1&amp;_ac_inputBackground=%23222&amp;_ac_buttonForeground=rgb%28255%2C+255%2C+255%29&amp;_ac_buttonBackground=%232e2db3&amp;_ac_link=%23e0e0e1&amp;_ac_linkHover=%23e0e0e1

**Comment by bristow** [comment]
Ah !! Donc, c'est k-prod qui gère le live et visiblement, il a bien livechat

@jocelynj je t'ai dérangé pour rien, on n'utilise pas notre instance.

**Comment by Jean-BaptisteC** [comment]
Je pense que le chat sera peut être généré sur nos serveurs au vu des infos qui sont mentionnées ici https://github.com/osm-fr/infrastructure/issues/558

**Comment by Jean-BaptisteC** [comment]
@jocelynj est ce que tu aurais le temps de mettre en place le chat peertube ou on abandonne l'idée pour cette année ?
