### ISSUE TITLE
Intégrer une page d'appel à contributions

### ISSUE THREAD

**Issue by BaptisteDixneuf** [osm-fr/sotmfr-website#2]

**Comment by vinber** [comment]
voici l'iframe : <iframe src="https://framaforms.org/proposition-dintervention-au-sotm-france-2020-1560878931" width="100%" height="800" border="0" ></iframe>  

attention, ce n'est pas ouvert pour autant encore :)

**Comment by naomap** [comment]
@BaptisteDixneuf pour moi c'est plus une feature qu'un enhancement :) 
Vu que le site n'est pas déployé on peut y intégrer le formulaire sans attendre.

**Comment by BaptisteDixneuf** [comment]
@naomap Oui, tu as raison 👍 . Je m'occupe de faire la page "Appel à contributions", maintenant.
