### ISSUE TITLE
Page programme : des modifs

### ISSUE THREAD

**Issue by bristow** [osm-fr/sotmfr-website#207]
@Jean-BaptisteC 

Peux-tu stp, adapter la page https://sotm2024.openstreetmap.fr/programme.html ainsi : 

- Voir le programme en plein écran : https://pretalx.com/sotm-fr-2024/schedule/,
- Utiliser l'application Android Giggity ([F-Droid](https://f-droid.org/fr/packages/net.gaast.giggity/), [Google Play](https://play.google.com/store/apps/details?id=net.gaast.giggity)) où vous trouverez l'ensemble du programme du SOTM,
- Le programme au format PDF sera bientôt disponible.

Les replays des conférences seront disponibles sur [Peertube](https://peertube.openstreetmap.fr/c/sotm_fr_2024/videos) quelques jours après l'événement.

Et au niveau 2 : 

## Programme en vue liste

L'iframe

**Comment by Jean-BaptisteC** [comment]
Les modifs sont en cours j'essaie de terminer à midi.
La PR a déja été créée

**Comment by Jean-BaptisteC** [comment]
Done
A voir dans une prochaine PR pour mentionner sur la page programme qu'un live sur peerturbe est prévu?

**Comment by bristow** [comment]
D'ailleurs, faudrait peut-être rajouter une mention comme quoi le programme peut encore subir des modifications. J'ai déjà modifié des choses.

**Comment by Jean-BaptisteC** [comment]
A mon sens c'est pas nécessaire tant qu'on a pas de programme en pdf.
