### ISSUE TITLE
Gérer les changements de dernière minute durant l'evt

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/sotmfr-website#212]
L'année dernière les changements de dernière minute avaient été demandées via des issues.
Est ce qu'on garde le même fonctionnement ou on utilise un canal de communication plus rapide ? (je peux m'abonner à toutes les notifs du repo Github, mais le mail d'alerte peut arriver entre 30 min et 1 heure après la création de l'issue).

Je propose de faire un point le jeudi dans l'après midi pour faire les derniers ajustements avant l'événement.

CC @bristow @vinber

**Comment by bristow** [comment]
Tu parles de quoi comme changement de dernière minute ?

En tous cas, je reçois les mails Github très très rapidement.

**Comment by Jean-BaptisteC** [comment]
Par exemple l'issue #146
Ok pour fonctionner avec Github

**Comment by bristow** [comment]
Le fait que l'on fasse beaucoup de choses sur Pretalx permet de ne pas avoir à toucher le jour J le site, il me semble.
