### ISSUE TITLE
Page Hébergement

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#221]
Bonjour,

Est-ce qu'il est possible de créer une page Hébergements ?
Pour la mise en forme, je laisse la main. Mais ne pas se prendre la tête.

Texte:

Si les hébergements Crous sont tous pris, nous vous proposons une liste d'hébergement bon marché sur Lyon:

[Pilo](https://www.pilohotels.com/)
Montée des Carmélites sur les pentes de la Croix-rousse (40 min. en TC depuis la Manu).
Quelques prix (base 3 nuits) : :
- lit capsule dans un dortoir de 16 personnes : 31.25/nuit/personne
- le dortoir complet de 14 personnes : 442.89/nuit (soit 31.60/p)
- lit capsule dans un dortoir de 4 personnes (sdb privée) : 39.33/nuit/personne
- dortoir complet de 4 personnes (sdb privée) : 157.32/nuit (soit 39.33/p)
Note : il existe des dortoirs réservés aux femmes aussi.
 
[Alter’hostel](https://www.alter-hostel.com/fr)
Quai Pierre Scize vers Vaise (40 min. en TC depuis la Manu).
Prix (base 3 nuits) :
- Lit Superposé dans Dortoir Mixte de 18 Lits : 29.33€/nuit/personne
- Lit Superposé dans Dortoir Mixte de 10 Lits : 31.33€/nuit/personne
- Lit dans Dortoir Mixte de 6 Lits : 37€/nuit/personne

[Slo hostel](https://slohostels.com/fr/lyon-saxe/) Rue Bonnefoi
M° Saxe-Gambetta (10 min en métro de la Manu)
Quelques prix :
- Lit dans un dortoir mixte pour 4 personnes : 35.47€/nuit/personne
- Dortoir pour 4 personnes : 141.87€/nuit

[Slo hostel](https://slohostels.com/fr/lyon-les-pentes/) Pentes de la Croix-Rousse
Rue Alsace-Lorraine M° Hôtel-de-Ville (30 min. depuis la manu en TC)
Quelques prix :
- Lit dans un dortoir mixte pour 10 personnes : 29,77€/nuit/personne
- Lit dans un dortoir mixte pour 6 personnes : 31.67€/nuit/personne
- Dortoir privé pour 6 personnes : 190€/nuit

[Le Flaneur](https://leflaneur-guesthouse.com/)
Rue Sébastien Gryphe (15 min. en TC depuis la Manu)
Quelques prix :
- Lit dans un dortoir mixte pour 16 personnes : 22.83€/nuit/personne
- Lit dans un dortoir mixte pour 10 personnes : 25.83€/nuit/personne
Remarque : petit-déjeuner inclus

[HO36](https://ho36.com/lyon-guillotiere/)
Rue Montesquieu, Tram Saint-André (15 min. en TC depuis la Manu)
Quelques prix :
- Lit en dortoir mixte de 6 personnes : 23.04€/nuit/personne
- Dortoir entier pour 6 personnes : 126.72€/nuit (soit 21.12/p)

[Hôtel F1 Lyon Gerland Vénissieux](https://all.accor.com/hotel/2306/index.fr.shtml)
Accessible directement par le T4 (arrêt États-Unis Viviani) :
Hôtel le moins cher de la ville (40 € par nuit)

[CISL ETHIC ETAPES](https://www.cis-lyon.com/)
pas loin de l’hôtel F1 (T4 arrêt Beauvisage CISL)
De 24€ à 54 €/pers/nuit selon la chambre…

**Comment by Jean-BaptisteC** [comment]
Le ticket peut être fermé

**Comment by vinber** [comment]
fait
