### ISSUE TITLE
Ajout logo niveau 2

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#224]
un nouveau logo pour le site, niveau 2

![logo-wemap](https://github.com/osm-fr/sotmfr-website/assets/890869/f7103e5d-268b-4cc9-a438-096f814aa506)

**Comment by Jean-BaptisteC** [comment]
Je n'arrive pas à télécharger l'image de mon côté.
Est il possible d'avoir le fichier image brut ou alors on reprend la même image que l'année dernière ?
