### ISSUE TITLE
Préparer le site post événement

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/sotmfr-website#229]
Todo

- [x] Cacher la page d'inscription
~- [ ] Retirer le live de la page d'accueil~
- [ ] Mettre à jour la page programmation avec les replays Peertube -> réutiliser ce qui à été fait l'année dernière.

**Comment by bristow** [comment]
Ce serait pas mal de mettre en ligne en page d'accueil cette vidéo : https://peertube.openstreetmap.fr/w/uEHxVUXBmqN49V9s4LJKmq

Avec un petit texte genre : Merci à toutes et tous, le SOTM 2024 en 1mn45 ↴

**Comment by Jean-BaptisteC** [comment]
Je pousse une PR pour ajouter les dernières vidéos, pour les retardataires on verra plus
