### ISSUE TITLE
Passer JB en mainteneur

### ISSUE THREAD

**Issue by bristow** [osm-fr/sotmfr-website#234]
Qui a la main pour passer @Jean-BaptisteC en mainteneur de ce dépot, ainsi que celui des attributions comme demandé ici : https://forum.openstreetmap.fr/t/appel-a-volontaires/25284/6?u=bristow

Merci !

**Comment by Jean-BaptisteC** [comment]
@vdct peut-être ?

**Comment by vinber** [comment]
normalement c'est fait

**Comment by vinber** [comment]
si c'est ok tu dois pouvoir fermer @Jean-BaptisteC
