### ISSUE TITLE
Mise à jour des bibliothèques

### ISSUE THREAD

**Issue by DarkVisenya** [osm-fr/sotmfr-website#25]
Je suis en train de mettre à jour les bibliothèques et de mettre à jour les différentes pages déjà créé.

J'ai également fait un brin de ménage des bibliothèques, des fonts, des images.

J'ai créé un fichier main.css, il contient des variables et le css custom de l'application. Seule ce fichier de style devra être modifié à l'avenir.

J'ai refacto le code et j'ai mis à jour les class des balises html selon les bibliothèques utilisés et les class créé

Je finis d'integrer la nouvelle page de @BaptisteDixneuf et je mergérai #17 le mr si vous validez les modifications de texte.

**Comment by tomao44** [comment]
Super, le site fonctionne bien. Je trouve le message d'accroche plus lisible.
Mes suggestions :

1. remplacer les `&nbsp` par `&nbsp;`
2. logo OSM en haut à gauche en trop : enlever
3. le titre de la barre de navigation n'est pas aligné avec les éléments du menu
4. il manque le bouton pour descendre
5. section about : le texte s'étale trop en largeur + corrections à inclure
6. footer : ne s'étale pas assez + doublon facebook

**Comment by DarkVisenya** [comment]
1/6. Oups... ;)
2. Le logo sur la nav est utile pour les pages autre que le home. Mais si d'autres personnes sont contre, le supprimer ne prends pas trop longtemps
4. Je l'ai supprimer volontairement car dans notre cas, le contenu est déjà visible donc le bouton perd son utilité

**Comment by tomao44** [comment]
La page `contribution.html` est trop étroite au format smartphone.
Il n'y a pas ce problème avec la carte de la page `infos.html`

**Comment by BaptisteDixneuf** [comment]
Pull request #17 merged. Je ferme l'issue.
