### ISSUE TITLE
Amélioration code

### ISSUE THREAD

**Issue by Alketta** [osm-fr/sotmfr-website#29]
Home : mettre en container à chaque section
Modifier column en 8 et 4 pour `about`
Fix exception footer home

**Comment by tomao44** [comment]
En mode mobile, l'image de pied de page et celle de la page des mentions légales sont trop grandes.
Il faudrait utiliser une _responsive image_.

**Comment by vinber** [comment]
> En mode mobile, l'image de pied de page et celle de la page des mentions légales sont trop grandes.
> Il faudrait utiliser une _responsive image_.

j'imagine que cela fait référence à ceci par exemple pour la page de mention légale

![image](https://user-images.githubusercontent.com/890869/158330688-4589461b-73f1-4573-819b-948424391a24.png)

**Comment by tomao44** [comment]
C'est corrigé dans le pull request #67 sur la page [mentions-legales](https://sotm2022.openstreetmap.fr/mentions-legales.html)
L'image du pied de page est réduite en mode mobile, reste à faire de même sur les autres pages.

**Comment by vinber** [comment]
bonjour,
l'organisation du sotm2023 reprend. je pense que l'on peux réfléchir à la même logique que les années précédentes et creuser les éléments d'améliorations.

je vois ici qu'il y avait des choses à faire sur d'autres pages, est-ce d'actualité ?
je vais aussi ouvrir une issue pour savoir qui est intéressé pour participer à la mise en place du pour 2023.

**Comment by bristow** [comment]
Je pense que tout est ok de ce côté, y a une issue dédiée pour la page responsive des soutiens.

Je clos cette issue.
