### ISSUE TITLE
Ajouter une page de mentions légales/RGPD

### ISSUE THREAD

**Issue by BaptisteDixneuf** [osm-fr/sotmfr-website#3]

**Comment by vinber** [comment]
Un début de politiques données perso ici : https://mypads.framapad.org/mypads/?/mypads/group/sotm-5m6wq27dv/pad/view/site-web-programmation-ku4hv57ul

**Comment by vinber** [comment]
et sans doute une part de ces mentions légales ici https://www.openstreetmap.fr/mentions-legales/
