### ISSUE TITLE
Ajouter un bandeau ANNULÉ sur la page d'accueil

### ISSUE THREAD

**Issue by naomap** [osm-fr/sotmfr-website#36]
Ajouter le mot ANNULÉ de manière visible sur la page d'accueil. En PJ le visuel diffusé sur Tweeter pour exemple.
![annulé](https://user-images.githubusercontent.com/6516063/78536389-0ea77a00-77ee-11ea-880d-8a8594219676.jpg)

**Comment by DarkVisenya** [comment]
J'ai fait une proposition de texte. Est-ce que cela vous convient ?

**Comment by naomap** [comment]
L'annulation du SOTM est à l'ODJ du CA de l'asso OSM France ce soir, je propose qu'on attende demain pour valider le texte.
