### ISSUE TITLE
Créer une visualisation agrégeant les meilleurs rendus

### ISSUE THREAD

**Issue by overflorian** [osm-fr/sotmfr-website#38]
Je propose de remplacer la carte par défaut sur la page d'accueil d'openstreetmap.fr avec une carte custom qui déchire.

**Son but :** 
1. gagner en flexibilité pour s'adapter au contexte du moment 
2. mieux promouvoir la richesse des données au delà du rendu de base

## Rendu vecto de base
Cette carte serait composée d'un rendu de base vectoriel, adaptatif en fonction du contexte, par exemple :
- en ce moment on a des zones sous couvre-feu https://twitter.com/cq94/status/1319309566350397443 : je pense que ça devrait apparaître par défaut sur notre carte  
- pareil pour les zones sinistrées par l’inondation dans le sud de la France : on pourrait afficher temporairement les bâtiments détruits, ceux qui sont touchés ... 
- on a un projet du mois sur les défibrillateurs, on pourrait imaginer qu'ils s'affichent temporairement de manière plus proéminente avec un lien qui renvoi vers le site projetdumois.fr
- en montagne on devrait afficher les éléments d'été en été, les éléments d'hiver en hiver
- en période électorale on devrait afficher le découpage électoral et les bureaux de vote 
- ...

Je suis sûr que la communauté trouvera 1000 utilisations pour cette fonctionnalité

## Rendus thématiques
En plus de cela, on devrait proposer de switcher vers des rendus thématiques selon le zoom et l'emplacement :
- quand on zoome en bretagne, on devrait afficher la possibilité de switcher en breton, pareil pour l'Occitan en Occitanie
- quand on zoome sur les alpes en hiver, ça devrait proposer de switcher sur openpistemap. En été, sur le rendu rando avec lignes de courbes.
- près de la côte vers openseamap  
- sur les gares vers le rendu indoor  
- en ville vers les rendus vélo + transport
- ...

## Récap'
Vous l'avez compris, je vous propose de développer en combo :
- un rendu générique qui nous apporterait la flexibilité qui nous manque actuellement sur osm.org

Aujourd'hui on est hyper réactifs avec umap, mais le lien n'est pas partagé au delà d'un cercle restreint de geeks. Si le lien devenait openstreetmap.fr, je suis sûr que cet URL pourrait devenir un bookmark important pour tous les journalistes de France de Navarre  ...
- un agrégat de rendus thématiques présentés intelligemment et contextuellement

En plus d'un formidable démonstrateur, ce nouvel outil pourrait palier à un problème récurrent : il ne faut pas mapper pour le rendu mais dans le même temps la donnée non-rendu est souvent beaucoup moins considérée. Afficher des rendus temporaires et contextuels boostera donc les contributions spécifiques.

**Comment by vinber** [comment]
salut, je ne suis pas sur de comprendre ceci pour le sotm-fr, je fermen ne pas hésiter à reouvrir si besoin
