### ISSUE TITLE
Déployer le site sur sotm2022.openstreetmap.fr

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#41]
#39 en partant du travail de @ThomasG77 peut-on déployer le site ?

@jocelynj @ThomasG77 vous avez tout ce qu'il faut ?

**Comment by ThomasG77** [comment]
Normalement oui mais je n'ai pas la main pour le moment. La balle à ce jour est dans le camp de @jocelynj.

Je ne sais pas la politique pour avoir des droits pour ce genre de cas n'ayant pas échangé avec Jocelyn à ce propos.

**Comment by jocelynj** [comment]
J'ai déployé la version dispo sur git sur http://sotm2022.openstreetmap.fr.

Pour les futurs mises à jour, est-ce que @ThomasG77 pourrait m'envoyer une clé ssh pour que je créée un compte sur cette VM ?

**Comment by ThomasG77** [comment]
Merci. Pour ta gouverne, il y a une formule magique :) https://github.com/ThomasG77.keys
Tu peux essayer avec ton compte

**Comment by vinber** [comment]
je ferme
