### ISSUE TITLE
Info pratiques : le lien pointe vers la carte uMap en anglais

### ISSUE THREAD

**Issue by naomap** [osm-fr/sotmfr-website#43]
Sur la page https://sotm2022.openstreetmap.fr/infos.html, le lien "Voir en plein écran" sous la carte uMap est http://umap.openstreetmap.fr/en/map/state-of-the-map-france-2020_425303. Merci de le remplacer par le lien vesr la carte en français : http://umap.openstreetmap.fr/fr/map/state-of-the-map-france-2020_425303

**Comment by ThomasG77** [comment]
Corrigé côté code https://github.com/osm-fr/sotmfr-website/commit/4c5feadd1352720b68fdb7cfabc4ea99c68ca099 et déployé sur le site. Réouvre si problème

**Comment by naomap** [comment]
Nickel. Merci !
