### ISSUE TITLE
Intégrer la bannière web et le logo

### ISSUE THREAD

**Issue by naomap** [osm-fr/sotmfr-website#44]
Le logo et la bannière Web sont disponibles : https://nextcloud.openstreetmap.fr/index.php/s/B6HQQFQiAKRFnbs
Ils peuvent être intégrés au site. Il y a 2 versions de la bannière Web, l'une avec l'autre sans le logo – à choisir selon que le logo eset intégré séparément ou pas.

Merci d'actualiser la page d'accueil du site (et éventuellement sur les autres pages ou dans le pied de page ?).

**Comment by naomap** [comment]
Les informations sur la charte graphique, couleurs et polices, sont sur https://acrobat.adobe.com/link/track?uri=urn:aaid:scds:US:810441b4-dd54-3d42-b5a5-263b200cda95#pageNum=1

**Comment by naomap** [comment]
@marcelezd est-ce que tu pourrais prendre en charge ce ticket ? Si oui peux-tu le faire à court terme ? Cette question est juste pour savoir s'il faut qu'on cherche quelqu'un d'autre :)

**Comment by marcelezd** [comment]
Je veux bien. Je fais une proposition d'ici ce soir.

**Comment by ThomasG77** [comment]
Je ferme. Adressé par la PR #49, mergé depuis
