### ISSUE TITLE
Retirer l'hébergement dans le texte sur la page infos pratiques

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#45]
https://sotm2022.openstreetmap.fr/infos.html

retirer "Un hébergement en cité universitaire est prévu, les réservations se feront lors de l'inscription." La convention vient d'annuler la convention

**Comment by gendy54** [comment]
C'est fait

**Comment by vinber** [comment]
> C'est fait

Non, je ne parle pas de la carte mais du texte dessous
