### ISSUE TITLE
Lien pour les inscriptions

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#46]
Lien pour les inscriptions du SotmFR 2022 au choix selon le plus pratique:

- [https://openstreetmap.assoconnect.com/collect/description/225519-b-state-of-the-map-france-2022](https://openstreetmap.assoconnect.com/collect/description/225519-b-state-of-the-map-france-2022)
- `<iframe id="iframe_assoconnect" src="https://openstreetmap.assoconnect.com/collect/description/225519-b-state-of-the-map-france-2022?iframe=1" width="100%" style="overflow: hidden; border: 0; max-height: none;" scrolling="no" onload="window.location.href='#iframe_assoconnect'"></iframe><script>window.addEventListener("message", function(event) {if(event.data.action === "iframe.height" && event.origin === "https://openstreetmap.assoconnect.com"){document.getElementById("iframe_assoconnect").height = event.data.height;}});</script><style>#iframe_assoconnect{border: 0}</style>`

**Comment by vinber** [comment]
à mon avis c'est 

- [ ] sur une page comme en 2019 (https://sotm2019.openstreetmap.fr/inscription.html)
- [ ] puis ajout d'un lien sur la page d'accueil 

cela n'exclut pas de commencer à communiquer sur la page d'inscription @gendy54 ?

**Comment by gendy54** [comment]
Du coup, c'est possible de pousser la page en prod ce soir?
J'aimerai vraiment éviter de devoir donner un lien temporaire sur assoconnect.

**Comment by vinber** [comment]
yep, à @ThomasG77 maintenant (merci @marcelezd )

**Comment by vinber** [comment]
je ne suis pas sur d'avoir suivi.

#48 est passé mais https://sotm2022.openstreetmap.fr/inscription.html ne passe pas.

et sur la page d'accueil https://sotm2022.openstreetmap.fr/ rien de visible.

Est-ce @jocelynj qui doit pousser cela ensuite ?

**Comment by ThomasG77** [comment]
J'ai fait un mail à Jocelyn: plus d'accès au SSH. Sinon @cquest, si tu trouves le temps pour regarder, preneur de ton retour.

**Comment by jocelynj** [comment]
Je viens de modifier la config ipv6 de la VM, qui devrait maintenant être accessible.

Je vais regarder pour mettre à jour le site web directement.

**Comment by jocelynj** [comment]
Le lien https://sotm2022.openstreetmap.fr/inscription.html marche maintenant, merci d'avoir mis à jour le git :)

**Comment by ThomasG77** [comment]
La VM est toujours inaccessible de mon côté. Je t'avais fait un mail, Jocelyn avec les infos utilisées pour me connecter. Tiens-moi informé même si cela parait moins bloquant.

**Comment by gendy54** [comment]
Merci les gars!
Prochaine étape, mettre le programme prévisionnel. Je ferai une issue.

**Comment by naomap** [comment]
Quelle belle surprise ce matin en ouvrant https://sotm2022.openstreetmap.fr/index.html
Merci pour le travail ce week-end et la publication du site !
On peut fermer ce ticket.
