### ISSUE TITLE
L'appel à contributions est clos

### ISSUE THREAD

**Issue by naomap** [osm-fr/sotmfr-website#51]
Le formulaire intégré dans la page contribution.html est clos, et montre une erreur. 
Remplacer l'iframe par le texte "L'appel à contributions est maintenant clos. Le programme sera publié prochainement".
Autre option : supprimer cette page de la navbar.

**Comment by ThomasG77** [comment]
Voilà ce que cela donne. Dans la branche https://github.com/osm-fr/sotmfr-website/tree/remove-contribution-call

![Sélection_669](https://user-images.githubusercontent.com/642120/166107170-f9f4e79d-a5ad-43c2-ba2b-ea81e1b5bfc3.png)

**Comment by marcelezd** [comment]
Il y aura un lien programme dans le menu donc on peut l'enlever quand le programme sera publié pour garder trois entrées.

**Comment by ThomasG77** [comment]
Donc très court terme, je merge avec le design "bof" puis dès que programme intégré, on supprime la page.
Le but est d'avoir le site à jour avec le nouveau design.

**Comment by vinber** [comment]
ok,k je clos et on reprendra la bascule avec le programme ensuite, merci
