### ISSUE TITLE
Ajout PDF dans la page programme

### ISSUE THREAD

**Issue by ThomasG77** [osm-fr/sotmfr-website#55]
Pour faire suite à la publication du programme sous forme web

**Comment by gendy54** [comment]
Le programme .pdf sera finalisé lundi. On pourra l'ajouter également.

**Comment by gendy54** [comment]
Voici la version à mettre sur la page programme
[SOTM2022_PROGRAMME v4.pdf](https://github.com/osm-fr/sotmfr-website/files/8757902/SOTM2022_PROGRAMME.v4.pdf)
e

**Comment by ThomasG77** [comment]
Ajouté et déployé sur le site. N'hésite pas à me faire un retour sur le look, le texte ou toute autre remarque. Je ferais les changements en fonction.

**Comment by gendy54** [comment]
Je pense que le texte mériterait d'être plus lisible. Peut-être en gras serait suffisant?

**Comment by ThomasG77** [comment]
J'ai mis un retour à la ligne entre le texte et la table qui est filtrée pour tous les cas. Merci de m'indiquer votre préféré ou de me faire une autre suggestion.

**Des choix pour essayer de trancher**

1. Juste le retour à la ligne en plus mais style inchangé.

![Sélection_711](https://user-images.githubusercontent.com/642120/169918744-f393bb16-f11b-4052-9612-88a5bcad34f8.png)

2. Un aperçu avec gras seul de changé

![Sélection_710](https://user-images.githubusercontent.com/642120/169918564-ac91ae6a-afed-491d-8897-0f9c47f100e1.png)

3. Gras + majuscule

![Sélection_706](https://user-images.githubusercontent.com/642120/169918262-aafef452-bde4-4059-a9a0-8cffbbd4697a.png)

4. Gras + taille 20

![Sélection_708](https://user-images.githubusercontent.com/642120/169918294-11f06658-2601-4b9c-a917-5380c813f6e0.png)

5. Gras + taille 20 + majuscule

![Sélection_707](https://user-images.githubusercontent.com/642120/169918374-939c4b57-279a-4152-b892-02b319c81ba1.png)

**Comment by gendy54** [comment]
Le plus lisible pour moi, c'est clairement le 4. Merci pour tes essais.

**Comment by ThomasG77** [comment]
Effectué. Je ferme l'issue car implémenté.
N'hésitez pas à commenter pour d'autres modifications.

**Comment by tomao44** [comment]
Voici une version avec uniquement le lien en gras + une image PDF :
![image](https://user-images.githubusercontent.com/17124868/169993716-3b6e1593-5a6f-42c3-b6df-2e2e5abff9db.png)

En version mobile :
![image](https://user-images.githubusercontent.com/17124868/169994100-ea450b25-3d94-4720-a944-ecfc33ac6fae.png)
