### ISSUE TITLE
Le programme en ligne ne montre pas tous les résumés

### ISSUE THREAD

**Issue by naomap** [osm-fr/sotmfr-website#56]
Seuls quelques résumés sont accessibles sur https://sotm2022.openstreetmap.fr/programme.html
Faudrait-il regénérer le JSON ou quelque chose comme ça ?

**Comment by marcelezd** [comment]
C'était fait à la main, je tente un script python qui peut remplir le json avec un export csv du .ods

**Comment by ThomasG77** [comment]
Mergé la mise à jour du programme et publié
