### ISSUE TITLE
Programme / Ajout des intervenants et résumé pour la plénière

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#58]
9h30-10h
De la carte blanche à la carte arc-en-ciel !
Capucine-Marin Dubroca-Voisin
Contributeurice aux projets Wikimédia depuis une dizaine d’années, Capucine-Marin est président·e  de Wikimédia France

10h-10h30
Carte blanche
Olivier Ertzscheid
Enseignant-chercheur français en sciences de l'information, Olivier Ertzscheid documente depuis plus de 17 ans les évolutions du web et de notre rapport à la connaissance au travers de son blog [affordance.info](http://affordance.info/) et de ses ouvrages et articles.

**Comment by tomao44** [comment]
En lien avec #60
Faut-il remplacer le titre _Intervention plénière_ par _De la carte blanche à la carte arc-en-ciel !_ ?
Les horaires sont différentes, faut-il les changer ?

**Comment by vinber** [comment]
>  Faut-il remplacer le titre Intervention plénière par De la carte blanche à la carte arc-en-ciel ! ?

Oui

et pour les horaires effectivement 
10h-10h30
De la carte blanche à la carte arc-en-ciel !
Capucine-Marin Dubroca-Voisin
Contributeurice aux projets Wikimédia depuis une dizaine d’années, Capucine-Marin est président·e de Wikimédia France

10h30-11h
Carte blanche
Olivier Ertzscheid
Enseignant-chercheur français en sciences de l'information, Olivier Ertzscheid documente depuis plus de 17 ans les évolutions du web et de notre rapport à la connaissance au travers de son blog [affordance.info](http://affordance.info/) et de ses ouvrages et articles.

**Comment by tomao44** [comment]
J'ai fait la correction sur la branche #60
