### ISSUE TITLE
Création catégorie

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#59]
Bonjour,

Est-ce que c'est possible, sans trop de travail pour vous de créer une catégorie rassemblant les 3 niveaux des conf?

- tout public
- intermédiaire
- expert

Actuellement c'est mélanger dans les thématiques.

**Comment by tomao44** [comment]
Oui c'est possible. Voici ce que ça donne en remontant les 3 niveaux de publique dans un groupe au dessus :
![image](https://user-images.githubusercontent.com/17124868/167314280-d28a1908-4338-4d62-94ec-e48db7f4a7da.png)

**Comment by gendy54** [comment]
Parfait. A pousser en prod ;)
