### ISSUE TITLE
Maj du programme

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#60]
J'ai détecté des coquilles mais je ne sais pas comment faire pour les corriger directement dans le code. Ca ne doit pas être compliqué de faire une PR là-dessus, mais...

- [ ] Il n'y a pas de salle TBD. C'est dans l'Amphi 2. Donc à corriger sur toutes les conf du vendredi.
- [ ] Pour la plénière_De la carte blanche à la carte arc-en-ciel !_ Capucine-Marin Dubroca-Voisin -Contributeurice aux projets Wikimédia depuis une dizaine d’années, Capucine-Marin est président·e  de Wikimédia France.
- [ ] Conf Données de marchabilité: coquille dans l'horaire

Il y aura d'autres corrections notamment sur la plénière, pour laquelle, je n'ai pas toutes les infos. Et pour les horaires.

En tout cas, c'est top ce que vous avez pu faire.
Merci ;)

**Comment by gendy54** [comment]
Je me disais bien que j'avais oublié qqch...

- [ ] Prez 49: Nouveau titre: Appropriation d’OSM par les acteurs publics : intégration, transformation et valorisation des données au sein du SIG des collectivités

**Comment by vinber** [comment]
- [ ] Prez 53, il est noté 11h30-11h00 et non pas 11h30-12h00

**Comment by tomao44** [comment]
- [ ] Prez 53 : c'est corrigé dans la branche mais pas encore sur master
- [ ]  prez 49 : le titre est déjà correct
