### ISSUE TITLE
Page soutiens, engagement sur 3 ans

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#69]
sans rien de pressé, le principal c'est la publication de la page de soutiens.

Certaines entreprises (cette année seulement magelium) s'engagent sur une convention de 3 ans à soutenir le sotm-fr (moins de paperasses, plus facile à gérer, beaucoup d'avantage pour tout le monde).

Je trouverais intéressant de pouvoir distinguer (genre un astérisque mais peut-être autre) qui renvoie une phrase du type "S'engage à soutenir l'évènement pendant 3 ans !"

avis ?

**Comment by vinber** [comment]
en préparation je me permets la petite relance de ce point :)

**Comment by vinber** [comment]
peut-on voir sur la page du logo magellium comment y adjoindre un signe de reconnaissance pour signaler que c'est sur 3 ans ? 

il y en a d'autres mais pour l'instant prenons ce cas d'usage.

Pour rappel, selon les dons il y a également 3 tailles différentes proprotionelles

Donc il y a un distingo par 
- par taille selon le montant
- par un signe selon la durée de l'engagement

**Comment by bristow** [comment]
ok, on en tient compte sur le site 2024. On a noté CartoCité et Magellium.

**Comment by bristow** [comment]
@Harfeur tu as une idée de comment on pourrait repérer les soutiens pluri-annuel ?

On peut faire une catégorie à part, mais on pourrait aussi rajouter une sorte de badge sur le logo avec l'année de départ et de fin. Cela servirai d'ailleurs pour le site des années suivantes...

**Comment by Harfeur** [comment]
J'ai ajouté une icône pour faire apparaître cette information. On peut y ajouter les années précises, mais je ne sais pas où trouver cette information.

4411b6c5b2c73845aeebd975f13b55f70123045d

**Comment by Jean-BaptisteC** [comment]
Sujet traité peut être fermé
