### ISSUE TITLE
La page Soutiens n'est accessible que depuis la page d'accueil

### ISSUE THREAD

**Issue by naomap** [osm-fr/sotmfr-website#70]
Le menu des pages Contributions, Programme, Inscriptions et Infos pratique ne propose pas l'entrée Soutiens. Seule les menus de la page d'accueil et d ela page Soutiens contiennent cette option.

**Comment by ThomasG77** [comment]
Changements effectués sur le dépôt et déployé sur le site officiel. Je te laisse fermer si OK.

**Comment by naomap** [comment]
Nickel
