### ISSUE TITLE
Exporter le programme vers Frab XML

### ISSUE THREAD

**Issue by tomao44** [osm-fr/sotmfr-website#71]
Suite au commentaire dans #33 : prévoir un export du programme vers un format compatible avec d'autres applications comme [Giggity](https://f-droid.org/fr/packages/net.gaast.giggity/).
Les fichiers XML supportées sont xcal/[Pentabarf](http://www.pentabarf.org/)/[frab](https://github.com/frab/frab).
Détail du format frab : [index.xml.haml](https://github.com/frab/frab/blob/main/app/views/public/schedule/index.xml.haml)

**Comment by tomao44** [comment]
J'ai fait un script NodeJs pour générer `schedule.xml`.
Voici le résultat dans Giggity :
![Screenshot_20220529-185950.png](https://user-images.githubusercontent.com/17124868/170882491-95408c00-f2f2-463e-8053-119005b9dd98.png)

**Comment by ThomasG77** [comment]
Tu peux pousser ton XML résultat et ton script, stp. A priori, cela marche selon ton retour.
