### ISSUE TITLE
Guide des interventions

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#72]
[SOTM2022_guide_interventions.pdf](https://github.com/osm-fr/sotmfr-website/files/8800680/SOTM2022_guide_interventions.pdf)

Guide à rajouter sur la page programme. Avec le texte de 2019.

![image](https://user-images.githubusercontent.com/10323517/171058381-b87a9486-21a7-45fe-9281-e35401aee732.png)

**Comment by ThomasG77** [comment]
Salut,

Fait et déployé mais ne présente pas la même forme (il n'y a plus ces blocs entourés comme en 2019). J'attends ton retour pour faire des modifs ou fermer l'issue.

**Comment by vinber** [comment]
non c'est ok je pense
