### ISSUE TITLE
erreur du logo jawg sur la page soutien

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#75]
ils ont changé de logo, je n'ai pas vérifié et donc c'est pas le bon. Sur le site on peut changer, sur les kakemonos, plus difficile ...

![jawgmaps-blue](https://user-images.githubusercontent.com/890869/171902863-70bc7a2d-43d2-4699-be35-bb9ba55b21db.png)
![jawgmaps-blue](https://user-images.githubusercontent.com/890869/171902866-7e215aa0-dce0-4bc8-a755-5bee14828c3a.svg)

Voici les bons logos !

**Comment by tomao44** [comment]
C'est corrigé.
