### ISSUE TITLE
Visibilité du dépot Github

### ISSUE THREAD

**Issue by JackNUMBER** [osm-fr/sotmfr-website#79]
Pour plus de visibilité du dépot Github il pourrait être intéressant de mettre un lien sur le site (en bas de page par exemple).

**Comment by vinber** [comment]
yep, je reprends ceci @tykayn tu peux jeter un oeil ?

(au passage, on pourrait aussi ajouter un compte mastodon d'osm-fr :) )

**Comment by tykayn** [comment]
hop c'est fait avec la PR #96
