### ISSUE TITLE
Changer la couleur :)

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#8]

**Comment by tomao44** [comment]
Sur le site d'origine, les couleurs utilisées sont :

-   **primary-dark: '#592123'**
-   **primary-light: '#982d22'**
-   links: '#592123'
-   links-light: '#982d22'
-   links-white: '#f5f0e9'
-   text: '#383838'
-   **background-light: '#fefef6'**
-   text-light: '#f5f0e9'

Les trois couleurs en gras sont les principales.

**Comment by tomao44** [comment]
Nouvelles couleurs :
   
- primary-dark: `#202055`
- primary-light: `#222296`
- links: `#202055`
- links-light: `#222296`
- links-white: `#e6e6f4`
- text: `#383838`
- background-light: `#fefef6`
- text-light: `#e6e6f4`

Et logo :
![image](https://user-images.githubusercontent.com/17124868/75634693-29e00200-5c10-11ea-92e3-771f4c980e0c.png)

**Comment by BaptisteDixneuf** [comment]
@tomao44 J'ai déployé sur cette url, une prévisualisation  => https://baptistedixneuf.github.io/sotmfr-website/2020/index.html 

![image](https://user-images.githubusercontent.com/6407530/75635111-cc4db480-5c13-11ea-8d45-e018e0300a34.png)

Pour moi, c'est Ok. 
Petite remarque : Est-ce que les contrastes sont correctes pour tout le monde ?

**Comment by DarkVisenya** [comment]
Je suis pas sur que le choix des couleurs effectués soit le plus adapté

**Comment by naomap** [comment]
Le fond de carte est en effet un peu sombre, il était plus lumineux sur http://sotm2020.openstreetmap.fr/ : d'où vient la différence, ce n'est pas la même image ?

**Comment by tomao44** [comment]
En effet, ce n'est pas la même image, l'image a été transformé en masque
(semi-transparent).
C'était pour s'adapter à la couleur du site, ici un dégradé de couleur est
ajouté via le code CSS.

Il faut faire des tests de rendu, avec différents dégradés de couleur pour
éclaircir, ou remettre l'image d'origine.
Le dégradé utilisé est :
https://colorzilla.com/gradient-editor/#202055+0,222296+50

ThomasO

Le lun. 2 mars 2020 à 12:34, Antoine Riche <notifications@github.com> a
écrit :

**Comment by tomao44** [comment]
Voici ce que ça donne avec l'image de fond de 2019 :
[image: image.png]

**Comment by naomap** [comment]
@tomao44 l'image n'a pas suivi apparemment (ou c'est moi qui suis pas ;-)

**Comment by tomao44** [comment]
Ha désolé, peut-être que la liste bloque l'image.
Voici plusieurs essais d'image de fond :
https://photos.app.goo.gl/3tKv4JgsmoWDJ1Lo6

Le lun. 2 mars 2020 à 20:10, Antoine Riche <notifications@github.com> a
écrit :

**Comment by naomap** [comment]
Perso j'aime bien la 3e... Sauf objection mets la 3e, ça le fait pour la V1 et on repassera par là après le travail de la graphiste.

**Comment by DarkVisenya** [comment]
Je reste très sceptique sur le thème bleu qui est sombre et froid.

**Comment by vinber** [comment]
c'est l'hiver, la graphiste amènera le printemps 😁

**Comment by tomao44** [comment]
Je trouve que l'appel à contribution devrait être plus visible sur la page d'accueil du site, c'est la page du moment.
Je propose d'ajouter `bg-primary` sur le lien dans le menu.

**Comment by overflorian** [comment]
je crois que le sujet n'est plus d'actualité. je ferme ce ticket.

**Comment by overflorian** [comment]
ah ben non, j'ai pas le droit ahah !

**Comment by DarkVisenya** [comment]
> ah ben non, j'ai pas le droit ahah !

Je vais fermer l'issue pour toi :)
Désolé la gestion du projet est limité au contributeur.
