### ISSUE TITLE
Mise en place du site pour 2023

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#81]
C'est reparti :)

si vous êtes intéressé par donner un coup de main, n'hésitez pas à vous signaler ici.

On reprend ce qui fonctionne, on voit si on peut améliorer des choses
- https://github.com/osm-fr/sotmfr-website/issues/79
- https://github.com/osm-fr/sotmfr-website/issues/69
- https://github.com/osm-fr/sotmfr-website/issues/29
- ...

et plus si cela semble nécessaire.

**Comment by vinber** [comment]
@jocelynj de mémoire il y a le sous domaine à créer puis 'dupliquer' le site ? Pas sur de moi

**Comment by ThomasG77** [comment]
@vinber Tu dupliques le dossier 2022 en 2023 puis tu demandes à @jocelynj de créer le sous-domaine. Il configure le fichier Apache pour faire pointer le domaine vers le dossier 2023 et on est reparti.

**Comment by jocelynj** [comment]
J'ai configuré DNS et VM pour que https://sotm2023.openstreetmap.fr/ soit disponible.

Il reste à mettre les bons fichiers dans `/data/project/sotm2023/sotmfr-website/2023`.

**Comment by vinber** [comment]
> @vinber Tu dupliques le dossier 2022 en 2023

ouarf ouarf, mais je ne sais même pas de quoi tu parles :)

**Comment by vinber** [comment]
> Il reste à mettre les bons fichiers dans /data/project/sotm2023/sotmfr-website/2023.

qui comprend et peut faire cela ?

**Comment by jocelynj** [comment]
Il faut juste me dire qui gérera la mise en prod du site, et j'ajoute les accès :) 

Je peux toujours mettre en place la première version après merge de la PR #82, mais ça serait bien d'avoir d'autres personnes qui pourront mettre à jour le site web.

**Comment by vinber** [comment]
salut,
que veut dire mettre en prod ? moi je ne sais pas faire.

Mais quelques personnes avaient l'air partantes. Est-ce toujours le cas @tomao44 @marcelezd @ThomasG77 ?

**Comment by vinber** [comment]
d'autres intéressés ?

**Comment by jocelynj** [comment]
Mettre en prod, ça veut dire mettre les fichiers sur la machine qui héberge le site. Je peux m'en occuper si on n'a pas d'autres volontaires.

Avant de mettre en prod, il faudrait que les fichiers soient disponibles ici. Le mieux serait d'accepter #82.

**Comment by ThomasG77** [comment]
Je peux m'en occuper sous réserve d'une correction sur le dossier

Après ssh sur la machine, je fais

```
cd /data/project/sotm2023/
git clone https://github.com/osm-fr/sotmfr-website.git
```
qui me renvoie

> fatal: could not create work tree dir 'sotmfr-website': Permission denied

Malheureusement, je n'ai pas les droits pour changer ceux sur le dossier /data/project/sotm2023/ (mon user me permet l'accès ssh, mais je n'ai jamais eu besoin d'un mot de passe). Si tu changes les droits @jocelynj sur ce dossier, je pourrais faire les MAJ ensuite.

**Comment by jocelynj** [comment]
@ThomasG77: je viens de t'ajouter au groupe sotm2023, qui posséde ce dossier.

**Comment by vinber** [comment]
donc nous avons @marcelezd @tykayn  et @JackNUMBER dispo pour donner un coup de main, merci beaucoup :)

@jocelynj ou @ThomasG77 pouvez vous leur donner les droits pour qu'il s'assigne des issues ? ou peut-être puis-je le faire mais je ne sais pas comment (sauf si cela a marché pour @tykayn tu peux t'assigner des issues ?)

**Comment by vinber** [comment]
je ferme ici
