### ISSUE TITLE
Liens à mettre à jour sur sotm 2023

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#83]
Bonjour,

Voici les liens à rajouter sur le site.
Échéance: mercredi soir pour un lancement jeudi.

### Appel à contribution:
https://framaforms.org/proposition-dintervention-au-sotm-france-2023-1675807136

<a href="https://framaforms.org/proposition-dintervention-au-sotm-france-2023-1675807136">Form</a>"

<iframe src="https://framaforms.org/proposition-dintervention-au-sotm-france-2023-1675807136" width="100%" height="800" border="0"></iframe>

**Comment by vdct** [comment]
> https://openstreetmap.assoconnect.com/collect/description/303968-b-state-of-the-map-france-2023

"Aucun formulaire ni billetterie n'a été publié dans cette page.", pas moyen de prévisualiser



> Appel à proposition ok mais inscription c'est tot non alors que l'on a pas la réponse du Crous pour l'hébergement ?

oui clairement. Pour lancer les inscriptions il faut être capable de proposer le combo inscription+hébergement, sinon ça sera un b**rdel à gérer

**Comment by gendy54** [comment]
OK pas de problème

**Comment by vinber** [comment]
de mémoire il y a une page à "activer" pour qu'elle devienne visible et intégrer l'iframe fournie par @gendy54 

@tomao44 @marcelezd @ThomasG77 un de vous pense pouvoir le faire ?

**Comment by vinber** [comment]
je crois que @tykayn est dessus. @ThomasG77  à accepter et déployer ? https://github.com/osm-fr/sotmfr-website/pull/87

**Comment by ThomasG77** [comment]
Mergé #87
Pour l'appel à contribution, j'ai mis une ancre HTML et déployé.
Le lien exact est https://sotm2023.openstreetmap.fr/#appel-a-contributions

**Comment by vinber** [comment]
Mais euh, y'avais une page non pour l'appel à contributions, dans le menu horizontal ?

**Comment by ThomasG77** [comment]
En fait, j'ai mergé la PE #87 mais je vois que tu t'attendais plutôt à https://web.archive.org/web/20220506100941/https://sotm2022.openstreetmap.fr/

**Comment by ThomasG77** [comment]
Mis à jour via commit pour page dédiée https://github.com/osm-fr/sotmfr-website/commit/4b21d71b9c5f62f6404adfa2c45b6f23531b0668

Redéployé vers https://sotm2023.openstreetmap.fr/index.html
