### ISSUE TITLE
Les logos sont en cours de création

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#84]
Si il y a des contraintes spécifiques pour le site, à préciser ici

**Comment by gendy54** [comment]
Voilà le logo ![2016-STOM-Marseille-logo-BAT-RVB](https://user-images.githubusercontent.com/10323517/228662796-39706ceb-2791-4997-ae48-e6ceb915e012.svg)
![2016-STOM-Marseille-logo-BAT-RVB](https://user-images.githubusercontent.com/10323517/228662798-8bad48ab-f252-4a71-a306-ad038b528fbb.png)

**Comment by vinber** [comment]
ok je ferme ici pour conserver les issues de discussions #103 et #85
