### ISSUE TITLE
Harmonisation police site web avec logo

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#85]
Je ne sais pas ce qui est possible pour vous.

Police SOTM 2023
https://fonts.google.com/specimen/Barlow+Condensed

Graisse logo Medium 500 (titre
texte courant ExtraLight 200 ou Light 300

Couleur bleu logo
#4674A7 bleu fond du logo
#C1E0F8 bleu ciel (filets)

Aplat bleu foncé

**Comment by vinber** [comment]
si je comprends bien, la demande est
- changer la police du site (si on peut éviter les appel à des google font c'est bien, comment peut on faire ?)
- mais également des changements de couleurs pour intégrer le logo. peut-être que mettre un logo ici peut aider
- je pense qu'il est préférable de faire une issue par demande (1 pour la police, 1 pour le changement de couleur avec le logo)

**Comment by marcelezd** [comment]
> changer la police du site (si on peut éviter les appel à des google font c'est bien, comment peut on faire ?)

On peut mettre les polices en local, comme fait pour bootstrap.

**Comment by marcelezd** [comment]
> > changer la police du site (si on peut éviter les appel à des google font c'est bien, comment peut on faire ?)
> 
> On peut mettre les polices en local, comme fait pour bootstrap.

Je viens de voir que celles déjà utilisées sont comme ça.

**Comment by gendy54** [comment]
![Capture d’écran du 2023-03-29 22-40-39](https://user-images.githubusercontent.com/10323517/228662358-9c1a226e-e5b6-42a3-b457-318ece57ce14.png)

Je viens d'avoir le détails définitif de la charte graphique par le graphiste.

**Comment by marcelezd** [comment]
> Je ne suis pas sûr pour les couleurs qui à priori sont à gérer dans les logos et pas dans le CSS lui-même.

c'est bien d'avoir une palette de couleur sur le site qui correspond au logo comme celle dans #44 l'année dernière

j'ai fait un exemple avec les couleurs au dessus dans #102

**Comment by JackNUMBER** [comment]
@gendy54 Est-ce qu'il y a un web design ou des éléments graphiques qui ont été réalisés avec [le logo](https://github.com/osm-fr/sotmfr-website/issues/84) et cette charte graphique ?

**Comment by vinber** [comment]
je ne crois pas.

peut-être utilisé aussi ceci 

![SOTM-2023-twitter-cover-1500x500px](https://user-images.githubusercontent.com/890869/229068601-c5c573f3-5ba7-4217-904e-be13599b8e46.png)

**Comment by JackNUMBER** [comment]
Merci @vinder pour l'image. Est-ce possible de l'avoir sans les textes et le logo par-dessus et non recadrée ?

**Comment by vinber** [comment]
> Merci @vinber pour l'image. Est-ce possible de l'avoir sans les textes et le logo par-dessus et non recadrée ?

aucune idée, je signale aux personnes concernées pour qu'elles viennent ici :)

**Comment by tomao44** [comment]
Sur Firefox, le texte blanc sur fond bleu est flou :
![image](https://user-images.githubusercontent.com/17124868/229277673-e60b9e5c-0b22-46ba-ae9d-8c99a45a2b8c.png)
J'ai testé [cette solution](https://stackoverflow.com/a/28376193) : `text-shadow: 0 0;`
et ça fonctionne sur mon poste :
![image](https://user-images.githubusercontent.com/17124868/229277864-d551e0d8-aab0-4f85-930d-4f682cf853c4.png)

Constatez-vous le même problème ?
Que pensez-vous de cette solution ?

**Comment by JackNUMBER** [comment]
> Sur Firefox, le texte blanc sur fond bleu est flou : ![image](https://user-images.githubusercontent.com/17124868/229277673-e60b9e5c-0b22-46ba-ae9d-8c99a45a2b8c.png) J'ai testé [cette solution](https://stackoverflow.com/a/28376193) : `text-shadow: 0 0;` et ça fonctionne sur mon poste : ![image](https://user-images.githubusercontent.com/17124868/229277864-d551e0d8-aab0-4f85-930d-4f682cf853c4.png)
> 
> Constatez-vous le même problème ? Que pensez-vous de cette solution ?

Peut-être créer une autre issue ?
Je pense qu'il faudrait en premier lieu utiliser la propriété css qui correspond à ce cas : `font-smoothing` (avec des préfixes navigateur)

**Comment by marcelezd** [comment]
> Je pense qu'il faudrait en premier lieu utiliser la propriété css qui correspond à ce cas : `font-smoothing` (avec des préfixes navigateur)

[Ça ne fonctionne pas sur tous les navigateurs.](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth)


Je pense que c'est parce que le texte est fin (300) donc l'antialiasing le rend flou.

En haut texte en 300, milieu en 400, bas 300 avec `text-shadow: 0 0;`
![image](https://user-images.githubusercontent.com/59266536/229359000-a97143cf-478d-4611-9419-179e5f4e4625.png)

`text-shadow` rajoute une bordure, ce qui rend le texte plus gras :
![image](https://user-images.githubusercontent.com/59266536/229359019-410cde9d-a599-4511-b583-7258c302db43.png)

on pourrait passer le texte en 400 pour le rendre plus lisible (et peut-être augmenter un peu la taille de la police, comme elle est en condensed elle est moins lisible en petit)

**Comment by JackNUMBER** [comment]
Passer en `400` aurait la même finalité que le text-shadow, faisons cela !

Je suis pour augmenter la taille de texte. 
Ici une démo de Barlow Condensed, Barlow et Arial, cela parait très petit pour une même font-size :

![image](https://user-images.githubusercontent.com/2306550/229635852-d82dde49-9fa1-4d7d-83c6-4147031cbac9.png)

Je propose de passer à `20px`, voire `22px`. Peut-être en réduisant légèrement la `line-height`.

**Comment by vinber** [comment]
Est ce que cette issue est toujours nécessaire ?

**Comment by JackNUMBER** [comment]
> Est ce que cette issue est toujours nécessaire ?

Oui, la correction citée dans nos derniers messages n'a pas encore été faite.

**Comment by JackNUMBER** [comment]
Avec #106 on pourrait clore cette issue 🙂
