### ISSUE TITLE
Maj mentions légales

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#86]
**A corriger:** 
c/o Maison des Associations du 2ème Arrondissement
23 rue Greneta
75002 Paris

SIRET : 841 037 583 00017

**Bonne version:**
c/o Maison des Associations Paris Centre
5 bis rue du Louvre
75001 PARIS
SIRET: 841 037 583 00025

**Comment by tomao44** [comment]
Correction effectuée dans #87
