### ISSUE TITLE
sortir la vidéo de la page d'accueil et l'appel à contributions

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#88]
Je pense que la video de l'ag n'a plus besoin d'être sur la page d'accueil de sotm2023

**Comment by ThomasG77** [comment]
Salut,

L'aperçu te fait croire que c'est la vidéo de l'AG. Si tu survoles le lien, tu vas voir qu'il pointe vers les vidéos 2022 de l'événement. Si on est explicite sur le fait que les gens peuvent voir/revoir les vidéos 2022, on peut garder sinon, lien à faire disparaitre même si c'est pour une autre raison que celle suggérée par le titre du ticket.

**Comment by vinber** [comment]
j'ai retiré l'ag, effectivement à mon avis on retire la vidéo de la page d'accueil

ainsi que l'iframe de l'appel à contribution à mon avis

**Comment by vinber** [comment]
merci
