### ISSUE TITLE
Ajouter une page soutiens

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#9]
http://sotm2019.openstreetmap.fr/sponsors.html

et on va commencer à récupérer les logos, en particulier de ceux qui ont qui convention de 3 ans avec nous

**Comment by BaptisteDixneuf** [comment]
Pour la page soutiens, on garde 2 parties ?

-Partenaires
-Soutiens

Pour les logos, je propose que le dépôt des logos soit réaliser dans le répertoire NextCloud suivant:
https://nextcloud.openstreetmap.fr/index.php/f/17841

@vinber 
Pour les soutiens, qui ont une convention de 3 ans avec l'association, est-il possible pour toi de déposer les logos dans ce répertoire ? Je suis preneur d'une autre solution, si cela n'est possible.

Pour les logos, je n'ai pas remarqué d'ordre particulier (alphabétique)? Si il y a un ordre dans les soutiens, merci de nous l'indiquer.

**Comment by vinber** [comment]
> Pour les soutiens, qui ont une convention de 3 ans avec l'association, est-il possible pour toi de déposer les logos dans ce répertoire ? Je suis preneur d'une autre solution, si cela n'est possible.

oui


> Pour les logos, je n'ai pas remarqué d'ordre particulier (alphabétique)? Si il y a un ordre dans les soutiens, merci de nous l'indiquer.

l'ordre est relatif à la taille et donc plus ou moins au montant !

La page de soutien est la page qui varie régulièrement au fur et à mesure que les nouveaux soutiens valident leur participation

Dans la partie soutien, il y a 3 "catégories", gros, moyen et petit : http://sotm2019.openstreetmap.fr/sponsors.html

est-ce que dans le dossier nextcloud on fait une arborescence suivant ces catégories ?

**Comment by BaptisteDixneuf** [comment]
> est-ce que dans le dossier nextcloud on fait une arborescence suivant ces catégories ?

Oui

**Comment by vinber** [comment]
> > est-ce que dans le dossier nextcloud on fait une arborescence suivant ces catégories ?
> 
> Oui

fait !

**Comment by vinber** [comment]
Et dans les soutiens, il y a 2 types de conventions 
- des conventions annuelles
- des conventions triannuelles

Peut-on avoir un signe distinctif (genre un astérisque) qui renvoie à une phrase du type Engagement à soutenir l'évènement pendant 3 ans !

**Comment by vinber** [comment]
Nous avons quelques retours de sponsors, peut-on commencer à les afficher ?

**Comment by naomap** [comment]
Est-ce qu'on inclut dans la page Soutiens un appel à soutenir SOTM, en expliquant à quoi ça sert ?

**Comment by vinber** [comment]
pourquoi pas mais en mode discret car franchement il n'est pas utile, je pense, de courrir après des sous !

**Comment by tomao44** [comment]
Est-ce que la page soutiens fera partie de la page d'accueil ([SotM 2019](https://2019.stateofthemap.org/#sponsors)), ou sera sur une page différente ([SotM-FR 2019](http://sotm2019.openstreetmap.fr/sponsors.html)) ?

**Comment by vinber** [comment]
Bonne question !!! l'un n'excluant pas l'autre si ?

**Comment by vinber** [comment]
je relance le sujet, la page soutiens va être nécessaire.

Commençons à y réfléchir

**Comment by vinber** [comment]
Bonjour,
les accords de principe de plusieurs soutiens, sponsors sont en train d'arriver.

si je reprends le fonctionnement imaginé 

- [ ] a-t-on une personne qui est ok pour s'en occuper ?
- [ ] avoir une "page" pour voir à quoi cela ressemble en l'état (même si elle n'est pas référencée en page d'accueil
- [ ] s'assurer d'avoir 2 parties Partenaires et Soutiens
- [ ] coté partenaires, pour l'instant l'université, à creuser avec Aliiance Libre (@naomap ton avis ? dans ce cas on doit récupérer les logos)
- [ ] cotés soutiens (ils donnent directement des sous) / 3 tailles en fonction du montant (1 max, 2, intermédiaire, 3 minima <- ce n'est évidemment pas péjoratif). Le groupe soutien décide de ce "niveau" et le renseigne dans le dossier du nextcloud dédié (Nextcloud-osm-fr/SOTM/sotm-fr-2022/Soutiens-logos-conventions/1-Logos), l'ordre dans chaque niveau est comme on veut, cela peut-être alphabétique, où à la suite au fur et à mesure de l'arrivée,
- [ ] certains soutiens s'engagent sur 3 ans, nous imaginions un moyen de distinguer par signe distinctif (genre un astérisque) qui renvoie une phrase du type Engagement à soutenir l'évènement pendant 3 ans !

**Comment by ThomasG77** [comment]
Salut,

Côté code, dans cette branche https://github.com/osm-fr/sotmfr-website/tree/page-soutiens
Déployé mais pas dans le menu http://sotm2022.openstreetmap.fr/sponsors.html

**Comment by vinber** [comment]
merci @ThomasG77 

as-tu accès a ceci sur le nextcloud osm-fr ? /SOTM/sotm-fr-2022/Soutiens-logos-conventions/1-Logos

estcèe que cela te convient 3 tailles en fonction du montant (1 max, 2, intermédiaire, 3 minima <- ce n'est évidemment pas péjoratif). Le groupe soutien décide de ce "niveau" et le renseigne dans le dossier du nextcloud dédié (Nextcloud-osm-fr/SOTM/sotm-fr-2022/Soutiens-logos-conventions/1-Logos), l'ordre dans chaque niveau est comme on veut, cela peut-être alphabétique, où à la suite au fur et à mesure de l'arrivée,

veux-tu un autre moyen pour ajouter, classer, organiser les logos ?

**Comment by ThomasG77** [comment]
Salut,

Pour le moment, sauf erreur, je n'ai que des niveaux 2 et 3 dans le dossier 1-Logos. Je t'ai contacté en MP sur Twitter pour partager la capture pour être sûr que j'ai bien compris.
Pour mettre les logos et publier les soutiens, on déroulerait comment? Un échéancier précis? Pour le moment, même si j'ai produit une page, les infos ne sont pas celles à jour. Le but est de savoir quand je dois bouger sur ces points et surtout si c'est très rapidement.

**Comment by vinber** [comment]
salut,
non pour l'instant pas d'échéancier précis, je dirais au fil de l'eau, je peux te signaler au fur et à mesure que change les fichiers dans nextcloud !!!
le "gros" échéancier, c'est lorsque l'on mettra en ligne, mais pas avant 3-4 semaines, le temps d'avoir les réponses ... Ou alors on publie au fil de l'eau pour pousser à avoir les réponses (quoi vous n'êtes pas encore soutien de l'évènement de l'année, mais vous êtes fous ...)

**Comment by naomap** [comment]
J'ai ajouté le dossier Partenaire-Nantes-Université avec les variantes du logo de Nantes Université : PNG en blanc ou noir et 72 ou 300 dpi. Il y a aussi des fichiers vectoriels au format EPS : comment on convertit ça en SVG ?

**Comment by vinber** [comment]
je fais un petit up ici.

on commence à avoir quelques logos et soutiens confirmés.
Je ne pense pas que l'on va avoir une date précise pour l'ouverture de la page soutiens mais plutôt au fil de l'eau.

Peut-on donc construire la page avec l'état actuel des soutiens et partenaires ?

**Comment by gendy54** [comment]
Hello,

La liste des soutiens est définitive. Vous pouvez donc les intégrer sur le site internet du Sotm.
Le programme .pdf va être finalisé lundi.

**Comment by naomap** [comment]
Un volontaire pour la page Soutiens @BaptisteDixneuf @ThomasG77  @tomao44  ?

**Comment by tomao44** [comment]
Je peux m'en occuper.
Où puis-je trouver la liste des soutiens définitive avec les logos ?
En plus de la page des soutiens, faut-il ajouter quelquechose en page d'accueil ?

**Comment by ThomasG77** [comment]
Salut,

Voici le lien http://labs.webgeodatavore.com/partage/1-Logos.zip pour le contenu de SOTM/sotm-fr-2022/Soutiens-logos-conventions/1-Logos pour dépanner si tu n'as pas accès. J'ai vérifié qu'il n'y avait rien de confidentiel mais bien que les logos dans ce dossier.

**Comment by vinber** [comment]
>  En plus de la page des soutiens, faut-il ajouter quelquechose en page d'accueil ?

non pour moi tout est ok, merci pour cette page de soutiens, parfait !

je clos cette issue
