### ISSUE TITLE
retirer Co-président d'OpenStreetMap France

### ISSUE THREAD

**Issue by vinber** [osm-fr/sotmfr-website#91]
bonjour,
sur la page https://sotm2023.openstreetmap.fr/mentions-legales.html

peut-on remplacer svp :
> Directeur de publication : Vincent Bergeot, co-président d’OpenStreetMap France. 

par
 
`Directeur de publication : Vincent Bergeot, conseil d'administration d’OpenStreetMap France.`

**Comment by vinber** [comment]
@tykayn @ThomasG77 si je fais ce genre de correction moi même, cela casse quelque chose ?

https://github.com/osm-fr/sotmfr-website/commit/892a8683a4f51facef853bfb0fc4356d8e6ace23

**Comment by tykayn** [comment]
> @tykayn @ThomasG77 si je fais ce genre de correction moi même, cela casse quelque chose ?
> 
> [892a868](https://github.com/osm-fr/sotmfr-website/commit/892a8683a4f51facef853bfb0fc4356d8e6ace23)

ça ne devrait rien casser :) tu peux y aller

**Comment by ThomasG77** [comment]
Redéployé. Je ferme le ticket
