### ISSUE TITLE
Amélioration page d'accueil

### ISSUE THREAD

**Issue by gendy54** [osm-fr/sotmfr-website#99]
Hello,

Dans la page d'accueil
![Capture d’écran du 2023-03-29 22-46-44](https://user-images.githubusercontent.com/10323517/228663554-df143786-965f-4627-8b79-8332738cfe8a.png)

Après Marseille, rajouter "Campus Faculté Sciences du sport, Luminy"

**Comment by ThomasG77** [comment]
Hello, cela te va (cf image jointe)? Histoire de savoir avant de changer réellement le code en dur.

![Aperçu possible](https://user-images.githubusercontent.com/642120/228667083-46e36704-a9db-45cb-a331-63332d05a960.png)

**Comment by gendy54** [comment]
Parfait!
